// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.emsi
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class CONTEXT : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"CONTEXT\",\"namespace\":\"eu.driver.model.emsi\",\"fields\":[{\"" +
				"name\":\"ID\",\"type\":\"string\",\"source\":\"element ID\"},{\"name\":\"MODE\",\"type\":\"string\"" +
				",\"source\":\"element MODE\"},{\"name\":\"MSGTYPE\",\"type\":\"string\",\"source\":\"element MS" +
				"GTYPE\"},{\"name\":\"CREATION\",\"type\":[\"null\",\"long\"],\"source\":\"element CREATION\"},{" +
				"\"name\":\"LINK\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"LINKCONTEX" +
				"T\",\"namespace\":\"eu.driver.model.emsi\",\"fields\":[{\"name\":\"ID\",\"type\":\"string\",\"so" +
				"urce\":\"element ID\"},{\"name\":\"ROLE\",\"type\":[\"null\",\"string\"],\"source\":\"element RO" +
				"LE\"}]}},\"source\":\"element LINK\"},{\"name\":\"LEVEL\",\"type\":[\"null\",\"string\"],\"sourc" +
				"e\":\"element LEVEL\"},{\"name\":\"SECLASS\",\"type\":[\"null\",\"string\"],\"source\":\"element" +
				" SECLASS\"},{\"name\":\"FREETEXT\",\"type\":[\"null\",\"string\"],\"source\":\"element FREETEX" +
				"T\"},{\"name\":\"URGENCY\",\"type\":[\"null\",\"string\"],\"source\":\"element URGENCY\"},{\"nam" +
				"e\":\"ORIGIN\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"ORIGINCONTEXT\",\"namespace\":\"" +
				"eu.driver.model.emsi\",\"fields\":[{\"name\":\"ORG_ID\",\"type\":\"string\",\"source\":\"eleme" +
				"nt ORG_ID\"},{\"name\":\"USER_ID\",\"type\":[\"null\",\"string\"],\"source\":\"element USER_ID" +
				"\"},{\"name\":\"NAME\",\"type\":[\"null\",\"string\"],\"source\":\"element NAME\"}]}],\"source\":" +
				"\"element ORIGIN\"},{\"name\":\"EXTERNAL_INFO\",\"type\":{\"type\":\"array\",\"items\":{\"type\"" +
				":\"record\",\"name\":\"EXTERNAL_INFOCONTEXT\",\"namespace\":\"eu.driver.model.emsi\",\"fiel" +
				"ds\":[{\"name\":\"FREETEXT\",\"type\":[\"null\",\"string\"],\"source\":\"element FREETEXT\"},{\"" +
				"name\":\"URI\",\"type\":\"string\",\"source\":\"element URI\"},{\"name\":\"TYPE\",\"type\":[\"null" +
				"\",\"string\"],\"source\":\"element TYPE\"}]}},\"source\":\"element EXTERNAL_INFO\"}]}");
		private string _ID;
		private string _MODE;
		private string _MSGTYPE;
		private System.Nullable<long> _CREATION;
		private IList<eu.driver.model.emsi.LINKCONTEXT> _LINK;
		private string _LEVEL;
		private string _SECLASS;
		private string _FREETEXT;
		private string _URGENCY;
		private eu.driver.model.emsi.ORIGINCONTEXT _ORIGIN;
		private IList<eu.driver.model.emsi.EXTERNAL_INFOCONTEXT> _EXTERNAL_INFO;
		public virtual Schema Schema
		{
			get
			{
				return CONTEXT._SCHEMA;
			}
		}
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				this._ID = value;
			}
		}
		public string MODE
		{
			get
			{
				return this._MODE;
			}
			set
			{
				this._MODE = value;
			}
		}
		public string MSGTYPE
		{
			get
			{
				return this._MSGTYPE;
			}
			set
			{
				this._MSGTYPE = value;
			}
		}
		public System.Nullable<long> CREATION
		{
			get
			{
				return this._CREATION;
			}
			set
			{
				this._CREATION = value;
			}
		}
		public IList<eu.driver.model.emsi.LINKCONTEXT> LINK
		{
			get
			{
				return this._LINK;
			}
			set
			{
				this._LINK = value;
			}
		}
		public string LEVEL
		{
			get
			{
				return this._LEVEL;
			}
			set
			{
				this._LEVEL = value;
			}
		}
		public string SECLASS
		{
			get
			{
				return this._SECLASS;
			}
			set
			{
				this._SECLASS = value;
			}
		}
		public string FREETEXT
		{
			get
			{
				return this._FREETEXT;
			}
			set
			{
				this._FREETEXT = value;
			}
		}
		public string URGENCY
		{
			get
			{
				return this._URGENCY;
			}
			set
			{
				this._URGENCY = value;
			}
		}
		public eu.driver.model.emsi.ORIGINCONTEXT ORIGIN
		{
			get
			{
				return this._ORIGIN;
			}
			set
			{
				this._ORIGIN = value;
			}
		}
		public IList<eu.driver.model.emsi.EXTERNAL_INFOCONTEXT> EXTERNAL_INFO
		{
			get
			{
				return this._EXTERNAL_INFO;
			}
			set
			{
				this._EXTERNAL_INFO = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ID;
			case 1: return this.MODE;
			case 2: return this.MSGTYPE;
			case 3: return this.CREATION;
			case 4: return this.LINK;
			case 5: return this.LEVEL;
			case 6: return this.SECLASS;
			case 7: return this.FREETEXT;
			case 8: return this.URGENCY;
			case 9: return this.ORIGIN;
			case 10: return this.EXTERNAL_INFO;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ID = (System.String)fieldValue; break;
			case 1: this.MODE = (System.String)fieldValue; break;
			case 2: this.MSGTYPE = (System.String)fieldValue; break;
			case 3: this.CREATION = (System.Nullable<long>)fieldValue; break;
			case 4: this.LINK = (IList<eu.driver.model.emsi.LINKCONTEXT>)fieldValue; break;
			case 5: this.LEVEL = (System.String)fieldValue; break;
			case 6: this.SECLASS = (System.String)fieldValue; break;
			case 7: this.FREETEXT = (System.String)fieldValue; break;
			case 8: this.URGENCY = (System.String)fieldValue; break;
			case 9: this.ORIGIN = (eu.driver.model.emsi.ORIGINCONTEXT)fieldValue; break;
			case 10: this.EXTERNAL_INFO = (IList<eu.driver.model.emsi.EXTERNAL_INFOCONTEXT>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
