// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.emsi
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class CONTACTRESOURCE : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"CONTACTRESOURCE\",\"namespace\":\"eu.driver.model.emsi\",\"fie" +
				"lds\":[{\"name\":\"TYPE\",\"type\":\"string\",\"source\":\"element TYPE\"},{\"name\":\"DETAIL\",\"" +
				"type\":\"string\",\"source\":\"element DETAIL\"}]}");
		private string _TYPE;
		private string _DETAIL;
		public virtual Schema Schema
		{
			get
			{
				return CONTACTRESOURCE._SCHEMA;
			}
		}
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				this._TYPE = value;
			}
		}
		public string DETAIL
		{
			get
			{
				return this._DETAIL;
			}
			set
			{
				this._DETAIL = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.TYPE;
			case 1: return this.DETAIL;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.TYPE = (System.String)fieldValue; break;
			case 1: this.DETAIL = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
