// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.emsi
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class EVENT : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"EVENT\",\"namespace\":\"eu.driver.model.emsi\",\"fields\":[{\"na" +
				"me\":\"ID\",\"type\":\"string\",\"source\":\"element ID\"},{\"name\":\"NAME\",\"type\":[\"null\",\"s" +
				"tring\"],\"source\":\"element NAME\"},{\"name\":\"MAIN_EVENT_ID\",\"type\":[\"null\",\"string\"" +
				"],\"source\":\"element MAIN_EVENT_ID\"},{\"name\":\"ETYPE\",\"type\":[\"null\",{\"type\":\"reco" +
				"rd\",\"name\":\"ETYPEEVENT\",\"namespace\":\"eu.driver.model.emsi\",\"fields\":[{\"name\":\"CA" +
				"TEGORY\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"source\":\"element CATEGORY\"},{\"" +
				"name\":\"ACTOR\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"source\":\"element ACTOR\"}" +
				",{\"name\":\"LOCTYPE\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"source\":\"element LO" +
				"CTYPE\"},{\"name\":\"ENV\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"source\":\"element" +
				" ENV\"}]}],\"source\":\"element ETYPE\"},{\"name\":\"SOURCE\",\"type\":[\"null\",\"string\"],\"s" +
				"ource\":\"element SOURCE\"},{\"name\":\"SCALE\",\"type\":[\"null\",\"string\"],\"source\":\"elem" +
				"ent SCALE\"},{\"name\":\"CERTAINTY\",\"type\":[\"null\",\"string\"],\"source\":\"element CERTA" +
				"INTY\"},{\"name\":\"DECL_DATIME\",\"type\":[\"null\",\"long\"],\"source\":\"element DECL_DATIM" +
				"E\"},{\"name\":\"OCC_DATIME\",\"type\":[\"null\",\"long\"],\"source\":\"element OCC_DATIME\"},{" +
				"\"name\":\"OBS_DATIME\",\"type\":[\"null\",\"long\"],\"source\":\"element OBS_DATIME\"},{\"name" +
				"\":\"STATUS\",\"type\":[\"null\",\"string\"],\"source\":\"element STATUS\"},{\"name\":\"RISK_ASS" +
				"ESSMNT\",\"type\":[\"null\",\"string\"],\"source\":\"element RISK_ASSESSMNT\"},{\"name\":\"REF" +
				"ERENCE\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"REFERENCEEVENT\"," +
				"\"namespace\":\"eu.driver.model.emsi\",\"fields\":[{\"name\":\"ORG_ID\",\"type\":\"string\",\"s" +
				"ource\":\"element ORG_ID\"},{\"name\":\"OTHER_EVENT_ID\",\"type\":{\"type\":\"array\",\"items\"" +
				":\"string\"},\"source\":\"element OTHER_EVENT_ID\"}]}},\"source\":\"element REFERENCE\"},{" +
				"\"name\":\"CASUALTIES\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"CASU" +
				"ALTIESEVENT\",\"namespace\":\"eu.driver.model.emsi\",\"fields\":[{\"name\":\"CONTEXT\",\"typ" +
				"e\":\"string\",\"source\":\"element CONTEXT\"},{\"name\":\"DATIME\",\"type\":[\"null\",\"long\"]," +
				"\"source\":\"element DATIME\"},{\"name\":\"DECONT\",\"type\":[\"null\",\"string\"],\"source\":\"e" +
				"lement DECONT\"},{\"name\":\"TRIAGERED\",\"type\":[\"null\",\"string\"],\"source\":\"element T" +
				"RIAGERED\"},{\"name\":\"TRIAGEYELLOW\",\"type\":[\"null\",\"string\"],\"source\":\"element TRI" +
				"AGEYELLOW\"},{\"name\":\"TRIAGEGREEN\",\"type\":[\"null\",\"string\"],\"source\":\"element TRI" +
				"AGEGREEN\"},{\"name\":\"TRIAGEBLACK\",\"type\":[\"null\",\"string\"],\"source\":\"element TRIA" +
				"GEBLACK\"},{\"name\":\"MISSING\",\"type\":[\"null\",\"string\"],\"source\":\"element MISSING\"}" +
				"]}},\"source\":\"element CASUALTIES\"},{\"name\":\"EVAC\",\"type\":{\"type\":\"array\",\"items\"" +
				":{\"type\":\"record\",\"name\":\"EVACEVENT\",\"namespace\":\"eu.driver.model.emsi\",\"fields\"" +
				":[{\"name\":\"DATIME\",\"type\":[\"null\",\"long\"],\"source\":\"element DATIME\"},{\"name\":\"DI" +
				"SPLACED\",\"type\":[\"null\",\"string\"],\"source\":\"element DISPLACED\"},{\"name\":\"EVACUAT" +
				"ED\",\"type\":[\"null\",\"string\"],\"source\":\"element EVACUATED\"}]}},\"source\":\"element " +
				"EVAC\"},{\"name\":\"EGEO\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"EG" +
				"EOEVENT\",\"namespace\":\"eu.driver.model.emsi\",\"fields\":[{\"name\":\"DATIME\",\"type\":[\"" +
				"null\",\"long\"],\"source\":\"element DATIME\"},{\"name\":\"TYPE\",\"type\":\"string\",\"source\"" +
				":\"element TYPE\"},{\"name\":\"POSITION\",\"type\":{\"type\":\"record\",\"name\":\"POSITION\",\"n" +
				"amespace\":\"eu.driver.model.emsi\",\"fields\":[{\"name\":\"LOC_ID\",\"type\":[\"null\",\"stri" +
				"ng\"],\"source\":\"element LOC_ID\"},{\"name\":\"NAME\",\"type\":[\"null\",\"string\"],\"source\"" +
				":\"element NAME\"},{\"name\":\"TYPE\",\"type\":[\"null\",\"string\"],\"source\":\"element TYPE\"" +
				"},{\"name\":\"COORDSYS\",\"type\":[\"null\",\"string\"],\"source\":\"element COORDSYS\"},{\"nam" +
				"e\":\"COORD\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"COORDType\",\"n" +
				"amespace\":\"eu.driver.model.emsi\",\"fields\":[{\"name\":\"LAT\",\"type\":\"double\",\"source" +
				"\":\"element LAT\"},{\"name\":\"LON\",\"type\":\"double\",\"source\":\"element LON\"},{\"name\":\"" +
				"HEIGHT\",\"type\":[\"null\",\"double\"],\"source\":\"element HEIGHT\"}]}},\"source\":\"element" +
				" COORD\"},{\"name\":\"HEIGHT_ROLE\",\"type\":[\"null\",\"string\"],\"source\":\"element HEIGHT" +
				"_ROLE\"},{\"name\":\"ADDRESS\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"source\":\"ele" +
				"ment ADDRESS\"}]},\"source\":\"element POSITION\"},{\"name\":\"WEATHER\",\"type\":{\"type\":\"" +
				"array\",\"items\":\"string\"},\"source\":\"element WEATHER\"},{\"name\":\"FREETEXT\",\"type\":[" +
				"\"null\",\"string\"],\"source\":\"element FREETEXT\"},{\"name\":\"ID\",\"type\":[\"null\",\"strin" +
				"g\"],\"source\":\"element ID\"},{\"name\":\"STATUS\",\"type\":[\"null\",\"string\"],\"source\":\"e" +
				"lement STATUS\"}]}},\"source\":\"element EGEO\"},{\"name\":\"CAUSE\",\"type\":[\"null\",\"stri" +
				"ng\"],\"source\":\"element CAUSE\"},{\"name\":\"FREETEXT\",\"type\":[\"null\",\"string\"],\"sour" +
				"ce\":\"element FREETEXT\"}]}");
		private string _ID;
		private string _NAME;
		private string _MAIN_EVENT_ID;
		private eu.driver.model.emsi.ETYPEEVENT _ETYPE;
		private string _SOURCE;
		private string _SCALE;
		private string _CERTAINTY;
		private System.Nullable<long> _DECL_DATIME;
		private System.Nullable<long> _OCC_DATIME;
		private System.Nullable<long> _OBS_DATIME;
		private string _STATUS;
		private string _RISK_ASSESSMNT;
		private IList<eu.driver.model.emsi.REFERENCEEVENT> _REFERENCE;
		private IList<eu.driver.model.emsi.CASUALTIESEVENT> _CASUALTIES;
		private IList<eu.driver.model.emsi.EVACEVENT> _EVAC;
		private IList<eu.driver.model.emsi.EGEOEVENT> _EGEO;
		private string _CAUSE;
		private string _FREETEXT;
		public virtual Schema Schema
		{
			get
			{
				return EVENT._SCHEMA;
			}
		}
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				this._ID = value;
			}
		}
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				this._NAME = value;
			}
		}
		public string MAIN_EVENT_ID
		{
			get
			{
				return this._MAIN_EVENT_ID;
			}
			set
			{
				this._MAIN_EVENT_ID = value;
			}
		}
		public eu.driver.model.emsi.ETYPEEVENT ETYPE
		{
			get
			{
				return this._ETYPE;
			}
			set
			{
				this._ETYPE = value;
			}
		}
		public string SOURCE
		{
			get
			{
				return this._SOURCE;
			}
			set
			{
				this._SOURCE = value;
			}
		}
		public string SCALE
		{
			get
			{
				return this._SCALE;
			}
			set
			{
				this._SCALE = value;
			}
		}
		public string CERTAINTY
		{
			get
			{
				return this._CERTAINTY;
			}
			set
			{
				this._CERTAINTY = value;
			}
		}
		public System.Nullable<long> DECL_DATIME
		{
			get
			{
				return this._DECL_DATIME;
			}
			set
			{
				this._DECL_DATIME = value;
			}
		}
		public System.Nullable<long> OCC_DATIME
		{
			get
			{
				return this._OCC_DATIME;
			}
			set
			{
				this._OCC_DATIME = value;
			}
		}
		public System.Nullable<long> OBS_DATIME
		{
			get
			{
				return this._OBS_DATIME;
			}
			set
			{
				this._OBS_DATIME = value;
			}
		}
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				this._STATUS = value;
			}
		}
		public string RISK_ASSESSMNT
		{
			get
			{
				return this._RISK_ASSESSMNT;
			}
			set
			{
				this._RISK_ASSESSMNT = value;
			}
		}
		public IList<eu.driver.model.emsi.REFERENCEEVENT> REFERENCE
		{
			get
			{
				return this._REFERENCE;
			}
			set
			{
				this._REFERENCE = value;
			}
		}
		public IList<eu.driver.model.emsi.CASUALTIESEVENT> CASUALTIES
		{
			get
			{
				return this._CASUALTIES;
			}
			set
			{
				this._CASUALTIES = value;
			}
		}
		public IList<eu.driver.model.emsi.EVACEVENT> EVAC
		{
			get
			{
				return this._EVAC;
			}
			set
			{
				this._EVAC = value;
			}
		}
		public IList<eu.driver.model.emsi.EGEOEVENT> EGEO
		{
			get
			{
				return this._EGEO;
			}
			set
			{
				this._EGEO = value;
			}
		}
		public string CAUSE
		{
			get
			{
				return this._CAUSE;
			}
			set
			{
				this._CAUSE = value;
			}
		}
		public string FREETEXT
		{
			get
			{
				return this._FREETEXT;
			}
			set
			{
				this._FREETEXT = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ID;
			case 1: return this.NAME;
			case 2: return this.MAIN_EVENT_ID;
			case 3: return this.ETYPE;
			case 4: return this.SOURCE;
			case 5: return this.SCALE;
			case 6: return this.CERTAINTY;
			case 7: return this.DECL_DATIME;
			case 8: return this.OCC_DATIME;
			case 9: return this.OBS_DATIME;
			case 10: return this.STATUS;
			case 11: return this.RISK_ASSESSMNT;
			case 12: return this.REFERENCE;
			case 13: return this.CASUALTIES;
			case 14: return this.EVAC;
			case 15: return this.EGEO;
			case 16: return this.CAUSE;
			case 17: return this.FREETEXT;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ID = (System.String)fieldValue; break;
			case 1: this.NAME = (System.String)fieldValue; break;
			case 2: this.MAIN_EVENT_ID = (System.String)fieldValue; break;
			case 3: this.ETYPE = (eu.driver.model.emsi.ETYPEEVENT)fieldValue; break;
			case 4: this.SOURCE = (System.String)fieldValue; break;
			case 5: this.SCALE = (System.String)fieldValue; break;
			case 6: this.CERTAINTY = (System.String)fieldValue; break;
			case 7: this.DECL_DATIME = (System.Nullable<long>)fieldValue; break;
			case 8: this.OCC_DATIME = (System.Nullable<long>)fieldValue; break;
			case 9: this.OBS_DATIME = (System.Nullable<long>)fieldValue; break;
			case 10: this.STATUS = (System.String)fieldValue; break;
			case 11: this.RISK_ASSESSMNT = (System.String)fieldValue; break;
			case 12: this.REFERENCE = (IList<eu.driver.model.emsi.REFERENCEEVENT>)fieldValue; break;
			case 13: this.CASUALTIES = (IList<eu.driver.model.emsi.CASUALTIESEVENT>)fieldValue; break;
			case 14: this.EVAC = (IList<eu.driver.model.emsi.EVACEVENT>)fieldValue; break;
			case 15: this.EGEO = (IList<eu.driver.model.emsi.EGEOEVENT>)fieldValue; break;
			case 16: this.CAUSE = (System.String)fieldValue; break;
			case 17: this.FREETEXT = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
