// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.emsi
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class POSITION : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""POSITION"",""namespace"":""eu.driver.model.emsi"",""fields"":[{""name"":""LOC_ID"",""type"":[""null"",""string""],""source"":""element LOC_ID""},{""name"":""NAME"",""type"":[""null"",""string""],""source"":""element NAME""},{""name"":""TYPE"",""type"":[""null"",""string""],""source"":""element TYPE""},{""name"":""COORDSYS"",""type"":[""null"",""string""],""source"":""element COORDSYS""},{""name"":""COORD"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""COORDType"",""namespace"":""eu.driver.model.emsi"",""fields"":[{""name"":""LAT"",""type"":""double"",""source"":""element LAT""},{""name"":""LON"",""type"":""double"",""source"":""element LON""},{""name"":""HEIGHT"",""type"":[""null"",""double""],""source"":""element HEIGHT""}]}},""source"":""element COORD""},{""name"":""HEIGHT_ROLE"",""type"":[""null"",""string""],""source"":""element HEIGHT_ROLE""},{""name"":""ADDRESS"",""type"":{""type"":""array"",""items"":""string""},""source"":""element ADDRESS""}]}");
		private string _LOC_ID;
		private string _NAME;
		private string _TYPE;
		private string _COORDSYS;
		private IList<eu.driver.model.emsi.COORDType> _COORD;
		private string _HEIGHT_ROLE;
		private IList<System.String> _ADDRESS;
		public virtual Schema Schema
		{
			get
			{
				return POSITION._SCHEMA;
			}
		}
		public string LOC_ID
		{
			get
			{
				return this._LOC_ID;
			}
			set
			{
				this._LOC_ID = value;
			}
		}
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				this._NAME = value;
			}
		}
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				this._TYPE = value;
			}
		}
		public string COORDSYS
		{
			get
			{
				return this._COORDSYS;
			}
			set
			{
				this._COORDSYS = value;
			}
		}
		public IList<eu.driver.model.emsi.COORDType> COORD
		{
			get
			{
				return this._COORD;
			}
			set
			{
				this._COORD = value;
			}
		}
		public string HEIGHT_ROLE
		{
			get
			{
				return this._HEIGHT_ROLE;
			}
			set
			{
				this._HEIGHT_ROLE = value;
			}
		}
		public IList<System.String> ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				this._ADDRESS = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.LOC_ID;
			case 1: return this.NAME;
			case 2: return this.TYPE;
			case 3: return this.COORDSYS;
			case 4: return this.COORD;
			case 5: return this.HEIGHT_ROLE;
			case 6: return this.ADDRESS;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.LOC_ID = (System.String)fieldValue; break;
			case 1: this.NAME = (System.String)fieldValue; break;
			case 2: this.TYPE = (System.String)fieldValue; break;
			case 3: this.COORDSYS = (System.String)fieldValue; break;
			case 4: this.COORD = (IList<eu.driver.model.emsi.COORDType>)fieldValue; break;
			case 5: this.HEIGHT_ROLE = (System.String)fieldValue; break;
			case 6: this.ADDRESS = (IList<System.String>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
