// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.emsi
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class REFERENCEEVENT : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"REFERENCEEVENT\",\"namespace\":\"eu.driver.model.emsi\",\"fiel" +
				"ds\":[{\"name\":\"ORG_ID\",\"type\":\"string\",\"source\":\"element ORG_ID\"},{\"name\":\"OTHER_" +
				"EVENT_ID\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"source\":\"element OTHER_EVENT" +
				"_ID\"}]}");
		private string _ORG_ID;
		private IList<System.String> _OTHER_EVENT_ID;
		public virtual Schema Schema
		{
			get
			{
				return REFERENCEEVENT._SCHEMA;
			}
		}
		public string ORG_ID
		{
			get
			{
				return this._ORG_ID;
			}
			set
			{
				this._ORG_ID = value;
			}
		}
		public IList<System.String> OTHER_EVENT_ID
		{
			get
			{
				return this._OTHER_EVENT_ID;
			}
			set
			{
				this._OTHER_EVENT_ID = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ORG_ID;
			case 1: return this.OTHER_EVENT_ID;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ORG_ID = (System.String)fieldValue; break;
			case 1: this.OTHER_EVENT_ID = (IList<System.String>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
