// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.emsi
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class RESOURCE : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"RESOURCE\",\"namespace\":\"eu.driver.model.emsi\",\"fields\":[{" +
				"\"name\":\"RTYPE\",\"type\":{\"type\":\"record\",\"name\":\"RTYPERESOURCE\",\"namespace\":\"eu.dr" +
				"iver.model.emsi\",\"fields\":[{\"name\":\"CLASS\",\"type\":\"string\",\"source\":\"element CLA" +
				"SS\"},{\"name\":\"CAPABILITY\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"source\":\"ele" +
				"ment CAPABILITY\"},{\"name\":\"CHARACTERISTICS\",\"type\":{\"type\":\"array\",\"items\":\"stri" +
				"ng\"},\"source\":\"element CHARACTERISTICS\"}]},\"source\":\"element RTYPE\"},{\"name\":\"ID" +
				"\",\"type\":[\"null\",\"string\"],\"source\":\"element ID\"},{\"name\":\"ORG_ID\",\"type\":[\"null" +
				"\",\"string\"],\"source\":\"element ORG_ID\"},{\"name\":\"NAME\",\"type\":[\"null\",\"string\"],\"" +
				"source\":\"element NAME\"},{\"name\":\"FREETEXT\",\"type\":[\"null\",\"string\"],\"source\":\"el" +
				"ement FREETEXT\"},{\"name\":\"RGEO\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\"," +
				"\"name\":\"RGEORESOURCE\",\"namespace\":\"eu.driver.model.emsi\",\"fields\":[{\"name\":\"DATI" +
				"ME\",\"type\":[\"null\",\"long\"],\"source\":\"element DATIME\"},{\"name\":\"TYPE\",\"type\":\"str" +
				"ing\",\"source\":\"element TYPE\"},{\"name\":\"POSITION\",\"type\":{\"type\":\"record\",\"name\":" +
				"\"POSITION\",\"namespace\":\"eu.driver.model.emsi\",\"fields\":[{\"name\":\"LOC_ID\",\"type\":" +
				"[\"null\",\"string\"],\"source\":\"element LOC_ID\"},{\"name\":\"NAME\",\"type\":[\"null\",\"stri" +
				"ng\"],\"source\":\"element NAME\"},{\"name\":\"TYPE\",\"type\":[\"null\",\"string\"],\"source\":\"" +
				"element TYPE\"},{\"name\":\"COORDSYS\",\"type\":[\"null\",\"string\"],\"source\":\"element COO" +
				"RDSYS\"},{\"name\":\"COORD\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"" +
				"COORDType\",\"namespace\":\"eu.driver.model.emsi\",\"fields\":[{\"name\":\"LAT\",\"type\":\"do" +
				"uble\",\"source\":\"element LAT\"},{\"name\":\"LON\",\"type\":\"double\",\"source\":\"element LO" +
				"N\"},{\"name\":\"HEIGHT\",\"type\":[\"null\",\"double\"],\"source\":\"element HEIGHT\"}]}},\"sou" +
				"rce\":\"element COORD\"},{\"name\":\"HEIGHT_ROLE\",\"type\":[\"null\",\"string\"],\"source\":\"e" +
				"lement HEIGHT_ROLE\"},{\"name\":\"ADDRESS\",\"type\":{\"type\":\"array\",\"items\":\"string\"}," +
				"\"source\":\"element ADDRESS\"}]},\"source\":\"element POSITION\"},{\"name\":\"FREETEXT\",\"t" +
				"ype\":[\"null\",\"string\"],\"source\":\"element FREETEXT\"},{\"name\":\"ID\",\"type\":[\"null\"," +
				"\"string\"],\"source\":\"element ID\"}]}},\"source\":\"element RGEO\"},{\"name\":\"QUANTITY\"," +
				"\"type\":[\"null\",\"double\"],\"source\":\"element QUANTITY\"},{\"name\":\"UM\",\"type\":[\"null" +
				"\",\"string\"],\"source\":\"element UM\"},{\"name\":\"STATUS\",\"type\":[\"null\",\"string\"],\"so" +
				"urce\":\"element STATUS\"},{\"name\":\"NATIONALITY\",\"type\":[\"null\",\"string\"],\"source\":" +
				"\"element NATIONALITY\"},{\"name\":\"CONTACT\",\"type\":{\"type\":\"array\",\"items\":{\"type\":" +
				"\"record\",\"name\":\"CONTACTRESOURCE\",\"namespace\":\"eu.driver.model.emsi\",\"fields\":[{" +
				"\"name\":\"TYPE\",\"type\":\"string\",\"source\":\"element TYPE\"},{\"name\":\"DETAIL\",\"type\":\"" +
				"string\",\"source\":\"element DETAIL\"}]}},\"source\":\"element CONTACT\"}]}");
		private eu.driver.model.emsi.RTYPERESOURCE _RTYPE;
		private string _ID;
		private string _ORG_ID;
		private string _NAME;
		private string _FREETEXT;
		private IList<eu.driver.model.emsi.RGEORESOURCE> _RGEO;
		private System.Nullable<double> _QUANTITY;
		private string _UM;
		private string _STATUS;
		private string _NATIONALITY;
		private IList<eu.driver.model.emsi.CONTACTRESOURCE> _CONTACT;
		public virtual Schema Schema
		{
			get
			{
				return RESOURCE._SCHEMA;
			}
		}
		public eu.driver.model.emsi.RTYPERESOURCE RTYPE
		{
			get
			{
				return this._RTYPE;
			}
			set
			{
				this._RTYPE = value;
			}
		}
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				this._ID = value;
			}
		}
		public string ORG_ID
		{
			get
			{
				return this._ORG_ID;
			}
			set
			{
				this._ORG_ID = value;
			}
		}
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				this._NAME = value;
			}
		}
		public string FREETEXT
		{
			get
			{
				return this._FREETEXT;
			}
			set
			{
				this._FREETEXT = value;
			}
		}
		public IList<eu.driver.model.emsi.RGEORESOURCE> RGEO
		{
			get
			{
				return this._RGEO;
			}
			set
			{
				this._RGEO = value;
			}
		}
		public System.Nullable<double> QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				this._QUANTITY = value;
			}
		}
		public string UM
		{
			get
			{
				return this._UM;
			}
			set
			{
				this._UM = value;
			}
		}
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				this._STATUS = value;
			}
		}
		public string NATIONALITY
		{
			get
			{
				return this._NATIONALITY;
			}
			set
			{
				this._NATIONALITY = value;
			}
		}
		public IList<eu.driver.model.emsi.CONTACTRESOURCE> CONTACT
		{
			get
			{
				return this._CONTACT;
			}
			set
			{
				this._CONTACT = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.RTYPE;
			case 1: return this.ID;
			case 2: return this.ORG_ID;
			case 3: return this.NAME;
			case 4: return this.FREETEXT;
			case 5: return this.RGEO;
			case 6: return this.QUANTITY;
			case 7: return this.UM;
			case 8: return this.STATUS;
			case 9: return this.NATIONALITY;
			case 10: return this.CONTACT;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.RTYPE = (eu.driver.model.emsi.RTYPERESOURCE)fieldValue; break;
			case 1: this.ID = (System.String)fieldValue; break;
			case 2: this.ORG_ID = (System.String)fieldValue; break;
			case 3: this.NAME = (System.String)fieldValue; break;
			case 4: this.FREETEXT = (System.String)fieldValue; break;
			case 5: this.RGEO = (IList<eu.driver.model.emsi.RGEORESOURCE>)fieldValue; break;
			case 6: this.QUANTITY = (System.Nullable<double>)fieldValue; break;
			case 7: this.UM = (System.String)fieldValue; break;
			case 8: this.STATUS = (System.String)fieldValue; break;
			case 9: this.NATIONALITY = (System.String)fieldValue; break;
			case 10: this.CONTACT = (IList<eu.driver.model.emsi.CONTACTRESOURCE>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
