// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.cap
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Alert : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Alert\",\"namespace\":\"eu.driver.model.cap\",\"fields\":[{\"nam" +
				"e\":\"identifier\",\"type\":\"string\"},{\"name\":\"sender\",\"type\":\"string\"},{\"name\":\"sent" +
				"\",\"doc\":\"TODO xs:dateTime Used pattern\",\"type\":\"string\"},{\"name\":\"status\",\"type\"" +
				":{\"type\":\"enum\",\"name\":\"Status\",\"namespace\":\"eu.driver.model.cap\",\"symbols\":[\"Ac" +
				"tual\",\"Exercise\",\"System\",\"Test\",\"Draft\"]}},{\"name\":\"msgType\",\"type\":{\"type\":\"en" +
				"um\",\"name\":\"MsgType\",\"namespace\":\"eu.driver.model.cap\",\"symbols\":[\"Alert\",\"Updat" +
				"e\",\"Cancel\",\"Ack\",\"Error\"]}},{\"name\":\"source\",\"default\":null,\"type\":[\"null\",\"str" +
				"ing\"]},{\"name\":\"scope\",\"type\":{\"type\":\"enum\",\"name\":\"Scope\",\"namespace\":\"eu.driv" +
				"er.model.cap\",\"symbols\":[\"Public\",\"Restricted\",\"Private\"]}},{\"name\":\"restriction" +
				"\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"addresses\",\"default\":null,\"t" +
				"ype\":[\"null\",\"string\"]},{\"name\":\"code\",\"default\":null,\"type\":[\"null\",\"string\",{\"" +
				"type\":\"array\",\"items\":\"string\"}]},{\"name\":\"note\",\"default\":null,\"type\":[\"null\",\"" +
				"string\"]},{\"name\":\"references\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":" +
				"\"incidents\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"info\",\"default\":nu" +
				"ll,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Info\",\"namespace\":\"eu.driver.model.ca" +
				"p\",\"fields\":[{\"name\":\"language\",\"default\":\"en-US\",\"type\":[\"string\",\"null\"]},{\"na" +
				"me\":\"category\",\"type\":[{\"type\":\"enum\",\"name\":\"Category\",\"namespace\":\"eu.driver.m" +
				"odel.cap\",\"symbols\":[\"Geo\",\"Met\",\"Safety\",\"Security\",\"Rescue\",\"Fire\",\"Health\",\"E" +
				"nv\",\"Transport\",\"Infra\",\"CBRNE\",\"Other\"]},{\"type\":\"array\",\"items\":\"Category\"}]}," +
				"{\"name\":\"event\",\"type\":\"string\"},{\"name\":\"responseType\",\"default\":null,\"type\":[\"" +
				"null\",{\"type\":\"enum\",\"name\":\"ResponseType\",\"namespace\":\"eu.driver.model.cap\",\"sy" +
				"mbols\":[\"Shelter\",\"Evacuate\",\"Prepare\",\"Execute\",\"Avoid\",\"Monitor\",\"Assess\",\"All" +
				"Clear\",\"None\"]},{\"type\":\"array\",\"items\":\"ResponseType\"}]},{\"name\":\"urgency\",\"typ" +
				"e\":{\"type\":\"enum\",\"name\":\"Urgency\",\"namespace\":\"eu.driver.model.cap\",\"symbols\":[" +
				"\"Immediate\",\"Expected\",\"Future\",\"Past\",\"Unknown\"]}},{\"name\":\"severity\",\"type\":{\"" +
				"type\":\"enum\",\"name\":\"Severity\",\"namespace\":\"eu.driver.model.cap\",\"symbols\":[\"Ext" +
				"reme\",\"Severe\",\"Moderate\",\"Minor\",\"Unknown\"]}},{\"name\":\"certainty\",\"type\":{\"type" +
				"\":\"enum\",\"name\":\"Certainty\",\"namespace\":\"eu.driver.model.cap\",\"symbols\":[\"Observ" +
				"ed\",\"Likely\",\"Possible\",\"Unlikely\",\"Unknown\"]}},{\"name\":\"audience\",\"default\":nul" +
				"l,\"type\":[\"null\",\"string\"]},{\"name\":\"eventCode\",\"default\":null,\"type\":[\"null\",{\"" +
				"type\":\"record\",\"name\":\"ValueNamePair\",\"namespace\":\"eu.driver.model.cap\",\"fields\"" +
				":[{\"name\":\"valueName\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"}]},{\"type" +
				"\":\"array\",\"items\":\"ValueNamePair\"}]},{\"name\":\"effective\",\"doc\":\"TODO: datetime\"," +
				"\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"onset\",\"doc\":\"TODO: datetime\"," +
				"\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"expires\",\"doc\":\"TODO: datetime" +
				"\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"senderName\",\"default\":null,\"" +
				"type\":[\"null\",\"string\"]},{\"name\":\"headline\",\"default\":null,\"type\":[\"null\",\"strin" +
				"g\"]},{\"name\":\"description\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"ins" +
				"truction\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"web\",\"doc\":\"TODO: an" +
				"yURI\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"contact\",\"default\":null," +
				"\"type\":[\"null\",\"string\"]},{\"name\":\"parameter\",\"default\":null,\"type\":[\"null\",\"Val" +
				"ueNamePair\",{\"type\":\"array\",\"items\":\"ValueNamePair\"}]},{\"name\":\"resource\",\"defau" +
				"lt\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Resource\",\"namespace\":\"eu.drive" +
				"r.model.cap\",\"fields\":[{\"name\":\"resourceDesc\",\"type\":\"string\"},{\"name\":\"size\",\"d" +
				"efault\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"uri\",\"doc\":\"TODO, anyURI\",\"default\"" +
				":null,\"type\":[\"null\",\"string\"]},{\"name\":\"mimeType\",\"doc\":\"The mimetype of the re" +
				"source!\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"deferUri\",\"default\":n" +
				"ull,\"type\":[\"null\",\"string\"]},{\"name\":\"digest\",\"default\":null,\"type\":[\"null\",\"st" +
				"ring\"]}]},{\"type\":\"array\",\"items\":\"Resource\"}]},{\"name\":\"area\",\"default\":null,\"t" +
				"ype\":[\"null\",{\"type\":\"record\",\"name\":\"Area\",\"namespace\":\"eu.driver.model.cap\",\"f" +
				"ields\":[{\"name\":\"areaDesc\",\"type\":\"string\"},{\"name\":\"polygon\",\"default\":null,\"ty" +
				"pe\":[\"null\",\"string\",{\"type\":\"array\",\"items\":\"string\"}]},{\"name\":\"circle\",\"defau" +
				"lt\":null,\"type\":[\"null\",\"string\",{\"type\":\"array\",\"items\":\"string\"}]},{\"name\":\"ge" +
				"ocode\",\"default\":null,\"type\":[\"null\",\"ValueNamePair\",{\"type\":\"array\",\"items\":\"Va" +
				"lueNamePair\"}]},{\"name\":\"altitude\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"na" +
				"me\":\"ceiling\",\"default\":null,\"type\":[\"null\",\"double\"]}]},{\"type\":\"array\",\"items\"" +
				":\"Area\"}]}]},{\"type\":\"array\",\"items\":\"Info\"}]}]}");
		private string _identifier;
		private string _sender;
		/// <summary>
		/// TODO xs:dateTime Used pattern
		/// </summary>
		private string _sent;
		private eu.driver.model.cap.Status _status;
		private eu.driver.model.cap.MsgType _msgType;
		private string _source;
		private eu.driver.model.cap.Scope _scope;
		private string _restriction;
		private string _addresses;
		private object _code;
		private string _note;
		private string _references;
		private string _incidents;
		private object _info;
		public virtual Schema Schema
		{
			get
			{
				return Alert._SCHEMA;
			}
		}
		public string identifier
		{
			get
			{
				return this._identifier;
			}
			set
			{
				this._identifier = value;
			}
		}
		public string sender
		{
			get
			{
				return this._sender;
			}
			set
			{
				this._sender = value;
			}
		}
		/// <summary>
		/// TODO xs:dateTime Used pattern
		/// </summary>
		public string sent
		{
			get
			{
				return this._sent;
			}
			set
			{
				this._sent = value;
			}
		}
		public eu.driver.model.cap.Status status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		public eu.driver.model.cap.MsgType msgType
		{
			get
			{
				return this._msgType;
			}
			set
			{
				this._msgType = value;
			}
		}
		public string source
		{
			get
			{
				return this._source;
			}
			set
			{
				this._source = value;
			}
		}
		public eu.driver.model.cap.Scope scope
		{
			get
			{
				return this._scope;
			}
			set
			{
				this._scope = value;
			}
		}
		public string restriction
		{
			get
			{
				return this._restriction;
			}
			set
			{
				this._restriction = value;
			}
		}
		public string addresses
		{
			get
			{
				return this._addresses;
			}
			set
			{
				this._addresses = value;
			}
		}
		public object code
		{
			get
			{
				return this._code;
			}
			set
			{
				this._code = value;
			}
		}
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				this._note = value;
			}
		}
		public string references
		{
			get
			{
				return this._references;
			}
			set
			{
				this._references = value;
			}
		}
		public string incidents
		{
			get
			{
				return this._incidents;
			}
			set
			{
				this._incidents = value;
			}
		}
		public object info
		{
			get
			{
				return this._info;
			}
			set
			{
				this._info = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.identifier;
			case 1: return this.sender;
			case 2: return this.sent;
			case 3: return this.status;
			case 4: return this.msgType;
			case 5: return this.source;
			case 6: return this.scope;
			case 7: return this.restriction;
			case 8: return this.addresses;
			case 9: return this.code;
			case 10: return this.note;
			case 11: return this.references;
			case 12: return this.incidents;
			case 13: return this.info;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.identifier = (System.String)fieldValue; break;
			case 1: this.sender = (System.String)fieldValue; break;
			case 2: this.sent = (System.String)fieldValue; break;
			case 3: this.status = (eu.driver.model.cap.Status)fieldValue; break;
			case 4: this.msgType = (eu.driver.model.cap.MsgType)fieldValue; break;
			case 5: this.source = (System.String)fieldValue; break;
			case 6: this.scope = (eu.driver.model.cap.Scope)fieldValue; break;
			case 7: this.restriction = (System.String)fieldValue; break;
			case 8: this.addresses = (System.String)fieldValue; break;
			case 9: this.code = (System.Object)fieldValue; break;
			case 10: this.note = (System.String)fieldValue; break;
			case 11: this.references = (System.String)fieldValue; break;
			case 12: this.incidents = (System.String)fieldValue; break;
			case 13: this.info = (System.Object)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
