// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.cap
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Resource : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Resource"",""namespace"":""eu.driver.model.cap"",""fields"":[{""name"":""resourceDesc"",""type"":""string""},{""name"":""size"",""default"":null,""type"":[""null"",""int""]},{""name"":""uri"",""doc"":""TODO, anyURI"",""default"":null,""type"":[""null"",""string""]},{""name"":""mimeType"",""doc"":""The mimetype of the resource!"",""default"":null,""type"":[""null"",""string""]},{""name"":""deferUri"",""default"":null,""type"":[""null"",""string""]},{""name"":""digest"",""default"":null,""type"":[""null"",""string""]}]}");
		private string _resourceDesc;
		private System.Nullable<int> _size;
		/// <summary>
		/// TODO, anyURI
		/// </summary>
		private string _uri;
		/// <summary>
		/// The mimetype of the resource!
		/// </summary>
		private string _mimeType;
		private string _deferUri;
		private string _digest;
		public virtual Schema Schema
		{
			get
			{
				return Resource._SCHEMA;
			}
		}
		public string resourceDesc
		{
			get
			{
				return this._resourceDesc;
			}
			set
			{
				this._resourceDesc = value;
			}
		}
		public System.Nullable<int> size
		{
			get
			{
				return this._size;
			}
			set
			{
				this._size = value;
			}
		}
		/// <summary>
		/// TODO, anyURI
		/// </summary>
		public string uri
		{
			get
			{
				return this._uri;
			}
			set
			{
				this._uri = value;
			}
		}
		/// <summary>
		/// The mimetype of the resource!
		/// </summary>
		public string mimeType
		{
			get
			{
				return this._mimeType;
			}
			set
			{
				this._mimeType = value;
			}
		}
		public string deferUri
		{
			get
			{
				return this._deferUri;
			}
			set
			{
				this._deferUri = value;
			}
		}
		public string digest
		{
			get
			{
				return this._digest;
			}
			set
			{
				this._digest = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.resourceDesc;
			case 1: return this.size;
			case 2: return this.uri;
			case 3: return this.mimeType;
			case 4: return this.deferUri;
			case 5: return this.digest;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.resourceDesc = (System.String)fieldValue; break;
			case 1: this.size = (System.Nullable<int>)fieldValue; break;
			case 2: this.uri = (System.String)fieldValue; break;
			case 3: this.mimeType = (System.String)fieldValue; break;
			case 4: this.deferUri = (System.String)fieldValue; break;
			case 5: this.digest = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
