// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.sim.entity.item
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class EnvironmentLabel : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""EnvironmentLabel"",""namespace"":""eu.driver.model.sim.entity.item"",""fields"":[{""name"":""subLabel"",""doc"":""Sub label of environment that this item has"",""type"":{""type"":""enum"",""name"":""EnvironmentSubLabel"",""namespace"":""eu.driver.model.sim.entity.item"",""symbols"":[""FOLIAGE"",""ROAD""]}}]}");
		/// <summary>
		/// Sub label of environment that this item has
		/// </summary>
		private eu.driver.model.sim.entity.item.EnvironmentSubLabel _subLabel;
		public virtual Schema Schema
		{
			get
			{
				return EnvironmentLabel._SCHEMA;
			}
		}
		/// <summary>
		/// Sub label of environment that this item has
		/// </summary>
		public eu.driver.model.sim.entity.item.EnvironmentSubLabel subLabel
		{
			get
			{
				return this._subLabel;
			}
			set
			{
				this._subLabel = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.subLabel;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.subLabel = (eu.driver.model.sim.entity.item.EnvironmentSubLabel)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
