// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.sim.entity.item
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class PersonType : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""PersonType"",""namespace"":""eu.driver.model.sim.entity.item"",""fields"":[{""name"":""gender"",""doc"":""Gender of the person"",""type"":{""type"":""enum"",""name"":""PersonSubType"",""namespace"":""eu.driver.model.sim.entity.item"",""symbols"":[""MALE"",""FEMALE"",""UNKNOWN""]}}]}");
		/// <summary>
		/// Gender of the person
		/// </summary>
		private eu.driver.model.sim.entity.item.PersonSubType _gender;
		public virtual Schema Schema
		{
			get
			{
				return PersonType._SCHEMA;
			}
		}
		/// <summary>
		/// Gender of the person
		/// </summary>
		public eu.driver.model.sim.entity.item.PersonSubType gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				this._gender = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.gender;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.gender = (eu.driver.model.sim.entity.item.PersonSubType)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
