// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.sim.entity.item
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class VehicleType : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""VehicleType"",""namespace"":""eu.driver.model.sim.entity.item"",""fields"":[{""name"":""subType"",""doc"":""Sub type of vehicles that this item is"",""type"":{""type"":""enum"",""name"":""VehicleSubType"",""namespace"":""eu.driver.model.sim.entity.item"",""symbols"":[""CAR"",""VAN"",""TRUCK"",""BOAT"",""PLANE"",""HELICOPTER"",""MOTORCYCLE""]}}]}");
		/// <summary>
		/// Sub type of vehicles that this item is
		/// </summary>
		private eu.driver.model.sim.entity.item.VehicleSubType _subType;
		public virtual Schema Schema
		{
			get
			{
				return VehicleType._SCHEMA;
			}
		}
		/// <summary>
		/// Sub type of vehicles that this item is
		/// </summary>
		public eu.driver.model.sim.entity.item.VehicleSubType subType
		{
			get
			{
				return this._subType;
			}
			set
			{
				this._subType = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.subType;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.subType = (eu.driver.model.sim.entity.item.VehicleSubType)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
