// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.core
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Heartbeat : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Heartbeat"",""namespace"":""eu.driver.model.core"",""fields"":[{""name"":""id"",""doc"":""Unique identifier of the connected application sending out this message"",""type"":""string""},{""name"":""alive"",""doc"":""UNIX Epoch time in milliseconds marking the time the connected application was last responding"",""type"":""long"",""logicalType"":""timestamp-millis""},{""name"":""origin"",""doc"":""Optional identifier from which device or location this message was sent (e.g. IP address, machine name)"",""default"":null,""type"":[""null"",""string""]}]}");
		/// <summary>
		/// Unique identifier of the connected application sending out this message
		/// </summary>
		private string _id;
		/// <summary>
		/// UNIX Epoch time in milliseconds marking the time the connected application was last responding
		/// </summary>
		private long _alive;
		/// <summary>
		/// Optional identifier from which device or location this message was sent (e.g. IP address, machine name)
		/// </summary>
		private string _origin;
		public virtual Schema Schema
		{
			get
			{
				return Heartbeat._SCHEMA;
			}
		}
		/// <summary>
		/// Unique identifier of the connected application sending out this message
		/// </summary>
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		/// <summary>
		/// UNIX Epoch time in milliseconds marking the time the connected application was last responding
		/// </summary>
		public long alive
		{
			get
			{
				return this._alive;
			}
			set
			{
				this._alive = value;
			}
		}
		/// <summary>
		/// Optional identifier from which device or location this message was sent (e.g. IP address, machine name)
		/// </summary>
		public string origin
		{
			get
			{
				return this._origin;
			}
			set
			{
				this._origin = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.alive;
			case 2: return this.origin;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.String)fieldValue; break;
			case 1: this.alive = (System.Int64)fieldValue; break;
			case 2: this.origin = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
