// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.core
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class OffsetFetchRequest : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"OffsetFetchRequest\",\"namespace\":\"eu.driver.model.core\",\"" +
				"fields\":[{\"name\":\"topic\",\"type\":\"string\"},{\"name\":\"offset\",\"default\":null,\"type\"" +
				":[\"null\",\"int\"]},{\"name\":\"partition\",\"default\":null,\"type\":[\"null\",\"int\"]}]}");
		private string _topic;
		private System.Nullable<int> _offset;
		private System.Nullable<int> _partition;
		public virtual Schema Schema
		{
			get
			{
				return OffsetFetchRequest._SCHEMA;
			}
		}
		public string topic
		{
			get
			{
				return this._topic;
			}
			set
			{
				this._topic = value;
			}
		}
		public System.Nullable<int> offset
		{
			get
			{
				return this._offset;
			}
			set
			{
				this._offset = value;
			}
		}
		public System.Nullable<int> partition
		{
			get
			{
				return this._partition;
			}
			set
			{
				this._partition = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.topic;
			case 1: return this.offset;
			case 2: return this.partition;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.topic = (System.String)fieldValue; break;
			case 1: this.offset = (System.Nullable<int>)fieldValue; break;
			case 2: this.partition = (System.Nullable<int>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
