// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.core
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class SessionMgmt : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""SessionMgmt"",""namespace"":""eu.driver.model.core"",""fields"":[{""name"":""trialId"",""doc"":""The unique ID of the Trial"",""type"":""string""},{""name"":""trialName"",""doc"":""The name of the Trial"",""type"":""string""},{""name"":""scenarioId"",""doc"":""The unique ID of the Scenario"",""type"":""string""},{""name"":""scenarioName"",""doc"":""The name of the Scenario"",""type"":""string""},{""name"":""sessionId"",""doc"":""The unique ID of the Session"",""type"":""string""},{""name"":""sessionName"",""doc"":""The name of the Session"",""type"":""string""},{""name"":""sessionState"",""doc"":""The state of the Session."",""type"":{""type"":""enum"",""name"":""SessionState"",""namespace"":""eu.driver.model.tm"",""symbols"":[""START"",""STOP""]}},{""name"":""comment"",""doc"":""An optional comment to the session state."",""default"":null,""type"":[""null"",""string""]}]}");
		/// <summary>
		/// The unique ID of the Trial
		/// </summary>
		private string _trialId;
		/// <summary>
		/// The name of the Trial
		/// </summary>
		private string _trialName;
		/// <summary>
		/// The unique ID of the Scenario
		/// </summary>
		private string _scenarioId;
		/// <summary>
		/// The name of the Scenario
		/// </summary>
		private string _scenarioName;
		/// <summary>
		/// The unique ID of the Session
		/// </summary>
		private string _sessionId;
		/// <summary>
		/// The name of the Session
		/// </summary>
		private string _sessionName;
		/// <summary>
		/// The state of the Session.
		/// </summary>
		private eu.driver.model.tm.SessionState _sessionState;
		/// <summary>
		/// An optional comment to the session state.
		/// </summary>
		private string _comment;
		public virtual Schema Schema
		{
			get
			{
				return SessionMgmt._SCHEMA;
			}
		}
		/// <summary>
		/// The unique ID of the Trial
		/// </summary>
		public string trialId
		{
			get
			{
				return this._trialId;
			}
			set
			{
				this._trialId = value;
			}
		}
		/// <summary>
		/// The name of the Trial
		/// </summary>
		public string trialName
		{
			get
			{
				return this._trialName;
			}
			set
			{
				this._trialName = value;
			}
		}
		/// <summary>
		/// The unique ID of the Scenario
		/// </summary>
		public string scenarioId
		{
			get
			{
				return this._scenarioId;
			}
			set
			{
				this._scenarioId = value;
			}
		}
		/// <summary>
		/// The name of the Scenario
		/// </summary>
		public string scenarioName
		{
			get
			{
				return this._scenarioName;
			}
			set
			{
				this._scenarioName = value;
			}
		}
		/// <summary>
		/// The unique ID of the Session
		/// </summary>
		public string sessionId
		{
			get
			{
				return this._sessionId;
			}
			set
			{
				this._sessionId = value;
			}
		}
		/// <summary>
		/// The name of the Session
		/// </summary>
		public string sessionName
		{
			get
			{
				return this._sessionName;
			}
			set
			{
				this._sessionName = value;
			}
		}
		/// <summary>
		/// The state of the Session.
		/// </summary>
		public eu.driver.model.tm.SessionState sessionState
		{
			get
			{
				return this._sessionState;
			}
			set
			{
				this._sessionState = value;
			}
		}
		/// <summary>
		/// An optional comment to the session state.
		/// </summary>
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				this._comment = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.trialId;
			case 1: return this.trialName;
			case 2: return this.scenarioId;
			case 3: return this.scenarioName;
			case 4: return this.sessionId;
			case 5: return this.sessionName;
			case 6: return this.sessionState;
			case 7: return this.comment;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.trialId = (System.String)fieldValue; break;
			case 1: this.trialName = (System.String)fieldValue; break;
			case 2: this.scenarioId = (System.String)fieldValue; break;
			case 3: this.scenarioName = (System.String)fieldValue; break;
			case 4: this.sessionId = (System.String)fieldValue; break;
			case 5: this.sessionName = (System.String)fieldValue; break;
			case 6: this.sessionState = (eu.driver.model.tm.SessionState)fieldValue; break;
			case 7: this.comment = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
