// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.core
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class TimingControl : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""TimingControl"",""namespace"":""eu.driver.model.core"",""fields"":[{""name"":""id"",""doc"":""sequence ID"",""type"":""long""},{""name"":""trialTime"",""doc"":""The date and time the distribution message was sent as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC."",""type"":""long"",""logicalType"":""timestamp-millis""},{""name"":""trialTimeSpeed"",""doc"":""The Trialtime speed factor."",""type"":""long""}]}");
		/// <summary>
		/// sequence ID
		/// </summary>
		private long _id;
		/// <summary>
		/// The date and time the distribution message was sent as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC.
		/// </summary>
		private long _trialTime;
		/// <summary>
		/// The Trialtime speed factor.
		/// </summary>
		private long _trialTimeSpeed;
		public virtual Schema Schema
		{
			get
			{
				return TimingControl._SCHEMA;
			}
		}
		/// <summary>
		/// sequence ID
		/// </summary>
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		/// <summary>
		/// The date and time the distribution message was sent as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC.
		/// </summary>
		public long trialTime
		{
			get
			{
				return this._trialTime;
			}
			set
			{
				this._trialTime = value;
			}
		}
		/// <summary>
		/// The Trialtime speed factor.
		/// </summary>
		public long trialTimeSpeed
		{
			get
			{
				return this._trialTimeSpeed;
			}
			set
			{
				this._trialTimeSpeed = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.trialTime;
			case 2: return this.trialTimeSpeed;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.Int64)fieldValue; break;
			case 1: this.trialTime = (System.Int64)fieldValue; break;
			case 2: this.trialTimeSpeed = (System.Int64)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
