// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.core
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class TimingControl : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""TimingControl"",""namespace"":""eu.driver.model.core"",""fields"":[{""name"":""command"",""doc"":""The type of command to switch the state of the time-service."",""type"":{""type"":""enum"",""name"":""Command"",""namespace"":""eu.driver.model.core"",""symbols"":[""Init"",""Start"",""Pause"",""Update"",""Stop"",""Reset""]}},{""name"":""trialTime"",""doc"":""The date and time the distribution message was sent as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC."",""default"":null,""type"":[""null"",""long""],""logicalType"":""timestamp-millis""},{""name"":""trialTimeSpeed"",""doc"":""The Trialtime speed factor."",""default"":null,""type"":[""null"",""float""]}]}");
		/// <summary>
		/// The type of command to switch the state of the time-service.
		/// </summary>
		private eu.driver.model.core.Command _command;
		/// <summary>
		/// The date and time the distribution message was sent as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC.
		/// </summary>
		private System.Nullable<long> _trialTime;
		/// <summary>
		/// The Trialtime speed factor.
		/// </summary>
		private System.Nullable<float> _trialTimeSpeed;
		public virtual Schema Schema
		{
			get
			{
				return TimingControl._SCHEMA;
			}
		}
		/// <summary>
		/// The type of command to switch the state of the time-service.
		/// </summary>
		public eu.driver.model.core.Command command
		{
			get
			{
				return this._command;
			}
			set
			{
				this._command = value;
			}
		}
		/// <summary>
		/// The date and time the distribution message was sent as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC.
		/// </summary>
		public System.Nullable<long> trialTime
		{
			get
			{
				return this._trialTime;
			}
			set
			{
				this._trialTime = value;
			}
		}
		/// <summary>
		/// The Trialtime speed factor.
		/// </summary>
		public System.Nullable<float> trialTimeSpeed
		{
			get
			{
				return this._trialTimeSpeed;
			}
			set
			{
				this._trialTimeSpeed = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.command;
			case 1: return this.trialTime;
			case 2: return this.trialTimeSpeed;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.command = (eu.driver.model.core.Command)fieldValue; break;
			case 1: this.trialTime = (System.Nullable<long>)fieldValue; break;
			case 2: this.trialTimeSpeed = (System.Nullable<float>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
