// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.core
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class TopicCreate : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""TopicCreate"",""namespace"":""eu.driver.model.core"",""fields"":[{""name"":""id"",""doc"":""Sender Client id"",""type"":""string""},{""name"":""topicName"",""doc"":""The name of the Topic to be created by the admin tool."",""type"":""string""},{""name"":""subscribeAllowed"",""doc"":""Indicates which clients are allowed to connect as subscriber."",""type"":[{""type"":""record"",""name"":""subscribeAllowed"",""namespace"":""eu.driver.model.core"",""fields"":[{""name"":""id"",""doc"":""Sender Client id"",""type"":""string""}]}]},{""name"":""publishedAllowed"",""doc"":""Indicates which clients are allowed to connect as publisher."",""type"":[{""type"":""record"",""name"":""publishedAllowed"",""namespace"":""eu.driver.model.core"",""fields"":[{""name"":""id"",""doc"":""Sender Client id"",""type"":""string""}]}]}]}");
		/// <summary>
		/// Sender Client id
		/// </summary>
		private string _id;
		/// <summary>
		/// The name of the Topic to be created by the admin tool.
		/// </summary>
		private string _topicName;
		/// <summary>
		/// Indicates which clients are allowed to connect as subscriber.
		/// </summary>
		private object _subscribeAllowed;
		/// <summary>
		/// Indicates which clients are allowed to connect as publisher.
		/// </summary>
		private object _publishedAllowed;
		public virtual Schema Schema
		{
			get
			{
				return TopicCreate._SCHEMA;
			}
		}
		/// <summary>
		/// Sender Client id
		/// </summary>
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		/// <summary>
		/// The name of the Topic to be created by the admin tool.
		/// </summary>
		public string topicName
		{
			get
			{
				return this._topicName;
			}
			set
			{
				this._topicName = value;
			}
		}
		/// <summary>
		/// Indicates which clients are allowed to connect as subscriber.
		/// </summary>
		public object subscribeAllowed
		{
			get
			{
				return this._subscribeAllowed;
			}
			set
			{
				this._subscribeAllowed = value;
			}
		}
		/// <summary>
		/// Indicates which clients are allowed to connect as publisher.
		/// </summary>
		public object publishedAllowed
		{
			get
			{
				return this._publishedAllowed;
			}
			set
			{
				this._publishedAllowed = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.topicName;
			case 2: return this.subscribeAllowed;
			case 3: return this.publishedAllowed;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.String)fieldValue; break;
			case 1: this.topicName = (System.String)fieldValue; break;
			case 2: this.subscribeAllowed = (System.Object)fieldValue; break;
			case 3: this.publishedAllowed = (System.Object)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
