// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.core
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class TopicRemoveRequest : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"TopicRemoveRequest\",\"namespace\":\"eu.driver.model.core\",\"" +
				"fields\":[{\"name\":\"topicName\",\"doc\":\"The name of the Topic to be created by the a" +
				"dmin tool.\",\"type\":\"string\"}]}");
		/// <summary>
		/// The name of the Topic to be created by the admin tool.
		/// </summary>
		private string _topicName;
		public virtual Schema Schema
		{
			get
			{
				return TopicRemoveRequest._SCHEMA;
			}
		}
		/// <summary>
		/// The name of the Topic to be created by the admin tool.
		/// </summary>
		public string topicName
		{
			get
			{
				return this._topicName;
			}
			set
			{
				this._topicName = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.topicName;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.topicName = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
