// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.tm
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public enum Phase
	{
		PROPER_NAME,
		INITIALIZATION,
		PREPARATION,
		PRE_INCIDENT,
		INCIDENT,
		POST_INCIDENT,
	}
}
