// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.edxl
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class EDXLDistribution : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""EDXLDistribution"",""namespace"":""eu.driver.model.edxl"",""fields"":[{""name"":""distributionID"",""doc"":""The unique identifier of this distribution message."",""type"":""string""},{""name"":""senderID"",""doc"":""The unique identifier of the sender."",""type"":""string""},{""name"":""dateTimeSent"",""doc"":""The date and time the distribution message was sent as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC."",""type"":""long"",""logicalType"":""timestamp-millis""},{""name"":""dateTimeExpires"",""doc"":""The date and time the distribution message should expire as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC."",""type"":""long"",""logicalType"":""timestamp-millis""},{""name"":""distributionStatus"",""doc"":""The action-ability of the message."",""type"":{""type"":""enum"",""name"":""DistributionStatus"",""namespace"":""eu.driver.model.edxl"",""symbols"":[""Actual"",""Exercise"",""System"",""Test"",""Unknown"",""NoAppropriateDefault""]}},{""name"":""distributionKind"",""doc"":""The function of the message."",""type"":{""type"":""enum"",""name"":""DistributionKind"",""namespace"":""eu.driver.model.edxl"",""symbols"":[""Report"",""Update"",""Cancel"",""Request"",""Response"",""Dispatch"",""Ack"",""Error"",""SensorConfiguration"",""SensorControl"",""SensorStatus"",""SensorDetection"",""Unknown"",""NoAppropriateDefault""]}}]}");
		/// <summary>
		/// The unique identifier of this distribution message.
		/// </summary>
		private string _distributionID;
		/// <summary>
		/// The unique identifier of the sender.
		/// </summary>
		private string _senderID;
		/// <summary>
		/// The date and time the distribution message was sent as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC.
		/// </summary>
		private long _dateTimeSent;
		/// <summary>
		/// The date and time the distribution message should expire as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC.
		/// </summary>
		private long _dateTimeExpires;
		/// <summary>
		/// The action-ability of the message.
		/// </summary>
		private eu.driver.model.edxl.DistributionStatus _distributionStatus;
		/// <summary>
		/// The function of the message.
		/// </summary>
		private eu.driver.model.edxl.DistributionKind _distributionKind;
		public virtual Schema Schema
		{
			get
			{
				return EDXLDistribution._SCHEMA;
			}
		}
		/// <summary>
		/// The unique identifier of this distribution message.
		/// </summary>
		public string distributionID
		{
			get
			{
				return this._distributionID;
			}
			set
			{
				this._distributionID = value;
			}
		}
		/// <summary>
		/// The unique identifier of the sender.
		/// </summary>
		public string senderID
		{
			get
			{
				return this._senderID;
			}
			set
			{
				this._senderID = value;
			}
		}
		/// <summary>
		/// The date and time the distribution message was sent as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC.
		/// </summary>
		public long dateTimeSent
		{
			get
			{
				return this._dateTimeSent;
			}
			set
			{
				this._dateTimeSent = value;
			}
		}
		/// <summary>
		/// The date and time the distribution message should expire as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC.
		/// </summary>
		public long dateTimeExpires
		{
			get
			{
				return this._dateTimeExpires;
			}
			set
			{
				this._dateTimeExpires = value;
			}
		}
		/// <summary>
		/// The action-ability of the message.
		/// </summary>
		public eu.driver.model.edxl.DistributionStatus distributionStatus
		{
			get
			{
				return this._distributionStatus;
			}
			set
			{
				this._distributionStatus = value;
			}
		}
		/// <summary>
		/// The function of the message.
		/// </summary>
		public eu.driver.model.edxl.DistributionKind distributionKind
		{
			get
			{
				return this._distributionKind;
			}
			set
			{
				this._distributionKind = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.distributionID;
			case 1: return this.senderID;
			case 2: return this.dateTimeSent;
			case 3: return this.dateTimeExpires;
			case 4: return this.distributionStatus;
			case 5: return this.distributionKind;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.distributionID = (System.String)fieldValue; break;
			case 1: this.senderID = (System.String)fieldValue; break;
			case 2: this.dateTimeSent = (System.Int64)fieldValue; break;
			case 3: this.dateTimeExpires = (System.Int64)fieldValue; break;
			case 4: this.distributionStatus = (eu.driver.model.edxl.DistributionStatus)fieldValue; break;
			case 5: this.distributionKind = (eu.driver.model.edxl.DistributionKind)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
