// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.system
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Log : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Log"",""namespace"":""eu.driver.model.system"",""fields"":[{""name"":""id"",""doc"":""Client id"",""type"":""string""},{""name"":""dateTimeSent"",""doc"":""The date and time the distribution message was sent as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC."",""type"":""long"",""logicalType"":""timestamp-millis""},{""name"":""level"",""doc"":""The action-ability of the message."",""type"":{""type"":""enum"",""name"":""Level"",""namespace"":""eu.driver.model.system"",""symbols"":[""DEBUG"",""INFO"",""WARN"",""ERROR"",""CRITICAL"",""SILLY""]}},{""name"":""log"",""doc"":""Actual log message"",""type"":""string""}]}");
		/// <summary>
		/// Client id
		/// </summary>
		private string _id;
		/// <summary>
		/// The date and time the distribution message was sent as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC.
		/// </summary>
		private long _dateTimeSent;
		/// <summary>
		/// The action-ability of the message.
		/// </summary>
		private eu.driver.model.system.Level _level;
		/// <summary>
		/// Actual log message
		/// </summary>
		private string _log;
		public virtual Schema Schema
		{
			get
			{
				return Log._SCHEMA;
			}
		}
		/// <summary>
		/// Client id
		/// </summary>
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		/// <summary>
		/// The date and time the distribution message was sent as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC.
		/// </summary>
		public long dateTimeSent
		{
			get
			{
				return this._dateTimeSent;
			}
			set
			{
				this._dateTimeSent = value;
			}
		}
		/// <summary>
		/// The action-ability of the message.
		/// </summary>
		public eu.driver.model.system.Level level
		{
			get
			{
				return this._level;
			}
			set
			{
				this._level = value;
			}
		}
		/// <summary>
		/// Actual log message
		/// </summary>
		public string log
		{
			get
			{
				return this._log;
			}
			set
			{
				this._log = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.dateTimeSent;
			case 2: return this.level;
			case 3: return this.log;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.String)fieldValue; break;
			case 1: this.dateTimeSent = (System.Int64)fieldValue; break;
			case 2: this.level = (eu.driver.model.system.Level)fieldValue; break;
			case 3: this.log = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
