// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.sim.entity.post
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public enum MediumTypes
	{
		CHAT,
		INCIDENT_REPORT,
		MAIL,
		MICROBLOG,
		NEWS,
		SITUATION_REPORT,
		SOCIAL_NETWORK,
		VIDEO,
	}
}
