// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.sim.support
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Address : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Address"",""namespace"":""eu.driver.model.sim.support"",""fields"":[{""name"":""street"",""doc"":""Optional street name including house number"",""default"":null,""type"":[""null"",""string""]},{""name"":""postalCode"",""doc"":""Optional postal code"",""default"":null,""type"":[""null"",""string""]},{""name"":""city"",""doc"":""Optional name of the city"",""default"":null,""type"":[""null"",""string""]},{""name"":""state"",""doc"":""Optional name of the state or province"",""default"":null,""type"":[""null"",""string""]},{""name"":""country"",""doc"":""Optional name of the country"",""default"":null,""type"":[""null"",""string""]}]}");
		/// <summary>
		/// Optional street name including house number
		/// </summary>
		private string _street;
		/// <summary>
		/// Optional postal code
		/// </summary>
		private string _postalCode;
		/// <summary>
		/// Optional name of the city
		/// </summary>
		private string _city;
		/// <summary>
		/// Optional name of the state or province
		/// </summary>
		private string _state;
		/// <summary>
		/// Optional name of the country
		/// </summary>
		private string _country;
		public virtual Schema Schema
		{
			get
			{
				return Address._SCHEMA;
			}
		}
		/// <summary>
		/// Optional street name including house number
		/// </summary>
		public string street
		{
			get
			{
				return this._street;
			}
			set
			{
				this._street = value;
			}
		}
		/// <summary>
		/// Optional postal code
		/// </summary>
		public string postalCode
		{
			get
			{
				return this._postalCode;
			}
			set
			{
				this._postalCode = value;
			}
		}
		/// <summary>
		/// Optional name of the city
		/// </summary>
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				this._city = value;
			}
		}
		/// <summary>
		/// Optional name of the state or province
		/// </summary>
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				this._state = value;
			}
		}
		/// <summary>
		/// Optional name of the country
		/// </summary>
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				this._country = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.street;
			case 1: return this.postalCode;
			case 2: return this.city;
			case 3: return this.state;
			case 4: return this.country;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.street = (System.String)fieldValue; break;
			case 1: this.postalCode = (System.String)fieldValue; break;
			case 2: this.city = (System.String)fieldValue; break;
			case 3: this.state = (System.String)fieldValue; break;
			case 4: this.country = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
