// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.sim.support
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Response : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Response"",""namespace"":""eu.driver.model.sim.support"",""fields"":[{""name"":""code"",""doc"":""Status code that best serves the response of the respondent, possibly similar to a HTTP response status code."",""type"":""int""},{""name"":""message"",""doc"":""Optional information accompanying the response code"",""default"":null,""type"":[""null"",""string""]},{""name"":""timestamp"",""doc"":""Optional UNIX Epoch time in milliseconds marking the time the respond was given"",""default"":null,""type"":[""null"",""long""],""logicalType"":""timestamp-millis""}]}");
		/// <summary>
		/// Status code that best serves the response of the respondent, possibly similar to a HTTP response status code.
		/// </summary>
		private int _code;
		/// <summary>
		/// Optional information accompanying the response code
		/// </summary>
		private string _message;
		/// <summary>
		/// Optional UNIX Epoch time in milliseconds marking the time the respond was given
		/// </summary>
		private System.Nullable<long> _timestamp;
		public virtual Schema Schema
		{
			get
			{
				return Response._SCHEMA;
			}
		}
		/// <summary>
		/// Status code that best serves the response of the respondent, possibly similar to a HTTP response status code.
		/// </summary>
		public int code
		{
			get
			{
				return this._code;
			}
			set
			{
				this._code = value;
			}
		}
		/// <summary>
		/// Optional information accompanying the response code
		/// </summary>
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				this._message = value;
			}
		}
		/// <summary>
		/// Optional UNIX Epoch time in milliseconds marking the time the respond was given
		/// </summary>
		public System.Nullable<long> timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				this._timestamp = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.code;
			case 1: return this.message;
			case 2: return this.timestamp;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.code = (System.Int32)fieldValue; break;
			case 1: this.message = (System.String)fieldValue; break;
			case 2: this.timestamp = (System.Nullable<long>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
