// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.sim.support
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class UnitLocation : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""UnitLocation"",""namespace"":""eu.driver.model.sim.support"",""fields"":[{""name"":""latitude"",""doc"":""In decimal degrees, ranging from [-90, 90] where 0 is the equator"",""type"":""double""},{""name"":""longitude"",""doc"":""In decimal degrees, ranging from (-180, 180] where 0 is the Prime Meridian (line going through the geographic north, Greenwich, and the geographic south)"",""type"":""double""},{""name"":""altitude"",""doc"":""Optional in meters, where 0 is the surface of the WGS84-based ellipsoid"",""default"":null,""type"":[""null"",""double""]}]}");
		/// <summary>
		/// In decimal degrees, ranging from [-90, 90] where 0 is the equator
		/// </summary>
		private double _latitude;
		/// <summary>
		/// In decimal degrees, ranging from (-180, 180] where 0 is the Prime Meridian (line going through the geographic north, Greenwich, and the geographic south)
		/// </summary>
		private double _longitude;
		/// <summary>
		/// Optional in meters, where 0 is the surface of the WGS84-based ellipsoid
		/// </summary>
		private System.Nullable<double> _altitude;
		public virtual Schema Schema
		{
			get
			{
				return UnitLocation._SCHEMA;
			}
		}
		/// <summary>
		/// In decimal degrees, ranging from [-90, 90] where 0 is the equator
		/// </summary>
		public double latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				this._latitude = value;
			}
		}
		/// <summary>
		/// In decimal degrees, ranging from (-180, 180] where 0 is the Prime Meridian (line going through the geographic north, Greenwich, and the geographic south)
		/// </summary>
		public double longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				this._longitude = value;
			}
		}
		/// <summary>
		/// Optional in meters, where 0 is the surface of the WGS84-based ellipsoid
		/// </summary>
		public System.Nullable<double> altitude
		{
			get
			{
				return this._altitude;
			}
			set
			{
				this._altitude = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.latitude;
			case 1: return this.longitude;
			case 2: return this.altitude;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.latitude = (System.Double)fieldValue; break;
			case 1: this.longitude = (System.Double)fieldValue; break;
			case 2: this.altitude = (System.Nullable<double>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
