// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.sim.support
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Velocity : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Velocity"",""namespace"":""eu.driver.model.sim.support"",""fields"":[{""name"":""yaw"",""doc"":""In decimal degrees, ranging from [0, 360) where 0 is pointing towards the geographic north. The yaw value is applied in a clockwise rotation over the item’s heading/yaw-axis. A yaw value of 90 makes the item face east, while a yaw of 270 makes it face west"",""type"":""double""},{""name"":""pitch"",""doc"":""In decimal degrees, ranging from [-90, 90] where 0 is perpendicular to the line between the item’s location and the centre of the WGS84-based ellipsoid. The pitch value is applied in a counter-clockwise rotation over the item’s pitch-axis. A pitch value of 45 makes the item face 45 degrees upwards, while a pitch of -20 makes it face 20 degrees downwards"",""type"":""double""},{""name"":""magnitude"",""doc"":""In meter per seconds, ranging from [0, infinity) where 0 is standing still relative to the earth’s rotation"",""type"":""double""}]}");
		/// <summary>
		/// In decimal degrees, ranging from [0, 360) where 0 is pointing towards the geographic north. The yaw value is applied in a clockwise rotation over the item’s heading/yaw-axis. A yaw value of 90 makes the item face east, while a yaw of 270 makes it face west
		/// </summary>
		private double _yaw;
		/// <summary>
		/// In decimal degrees, ranging from [-90, 90] where 0 is perpendicular to the line between the item’s location and the centre of the WGS84-based ellipsoid. The pitch value is applied in a counter-clockwise rotation over the item’s pitch-axis. A pitch value of 45 makes the item face 45 degrees upwards, while a pitch of -20 makes it face 20 degrees downwards
		/// </summary>
		private double _pitch;
		/// <summary>
		/// In meter per seconds, ranging from [0, infinity) where 0 is standing still relative to the earth’s rotation
		/// </summary>
		private double _magnitude;
		public virtual Schema Schema
		{
			get
			{
				return Velocity._SCHEMA;
			}
		}
		/// <summary>
		/// In decimal degrees, ranging from [0, 360) where 0 is pointing towards the geographic north. The yaw value is applied in a clockwise rotation over the item’s heading/yaw-axis. A yaw value of 90 makes the item face east, while a yaw of 270 makes it face west
		/// </summary>
		public double yaw
		{
			get
			{
				return this._yaw;
			}
			set
			{
				this._yaw = value;
			}
		}
		/// <summary>
		/// In decimal degrees, ranging from [-90, 90] where 0 is perpendicular to the line between the item’s location and the centre of the WGS84-based ellipsoid. The pitch value is applied in a counter-clockwise rotation over the item’s pitch-axis. A pitch value of 45 makes the item face 45 degrees upwards, while a pitch of -20 makes it face 20 degrees downwards
		/// </summary>
		public double pitch
		{
			get
			{
				return this._pitch;
			}
			set
			{
				this._pitch = value;
			}
		}
		/// <summary>
		/// In meter per seconds, ranging from [0, infinity) where 0 is standing still relative to the earth’s rotation
		/// </summary>
		public double magnitude
		{
			get
			{
				return this._magnitude;
			}
			set
			{
				this._magnitude = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.yaw;
			case 1: return this.pitch;
			case 2: return this.magnitude;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.yaw = (System.Double)fieldValue; break;
			case 1: this.pitch = (System.Double)fieldValue; break;
			case 2: this.magnitude = (System.Double)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
