// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.sim.entity
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Post : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Post\",\"namespace\":\"eu.driver.model.sim.entity\",\"fields\":" +
				"[{\"name\":\"guid\",\"doc\":\"Globally unique identifier for this post\",\"type\":\"string\"" +
				"},{\"name\":\"name\",\"doc\":\"Name of this post\",\"type\":\"string\"},{\"name\":\"owner\",\"doc" +
				"\":\"Identifier of the simulator currently responsible for this post\",\"type\":\"stri" +
				"ng\"},{\"name\":\"mediumType\",\"doc\":\"Type of crisis media medium this post was place" +
				"d on/in\",\"type\":{\"type\":\"enum\",\"name\":\"MediumTypes\",\"namespace\":\"eu.driver.model" +
				".sim.entity.post\",\"symbols\":[\"CHAT\",\"INCIDENT_REPORT\",\"MAIL\",\"MICROBLOG\",\"NEWS\"," +
				"\"SITUATION_REPORT\",\"SOCIAL_NETWORK\",\"VIDEO\"]}},{\"name\":\"mediumName\",\"doc\":\"Name " +
				"of the medium this post was placed on/in\",\"type\":\"string\"},{\"name\":\"header\",\"doc" +
				"\":\"Title of this post\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"intro\"," +
				"\"doc\":\"Introduction of this post\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"nam" +
				"e\":\"body\",\"doc\":\"The body text of this post\",\"type\":\"string\"},{\"name\":\"files\",\"d" +
				"oc\":\"Links to files attached to this post\",\"default\":null,\"type\":[\"null\",{\"type\"" +
				":\"array\",\"items\":\"string\"}]},{\"name\":\"visibleForParticipant\",\"doc\":\"Indication w" +
				"hether or not this post is visible for any participant\",\"type\":\"boolean\"},{\"name" +
				"\":\"senderName\",\"doc\":\"Name of the sender sending this post\",\"type\":\"string\"},{\"n" +
				"ame\":\"senderRole\",\"doc\":\"Reference to the role sending this post\",\"default\":null" +
				",\"type\":[\"null\",\"string\"]},{\"name\":\"recipients\",\"doc\":\"List of references to the" +
				" roles that should receive this post personally\",\"default\":null,\"type\":[\"null\",{" +
				"\"type\":\"array\",\"items\":\"string\"}]},{\"name\":\"date\",\"doc\":\"The fictive creation da" +
				"te and time of this post as the number of milliseconds from the unix epoch, 1 Ja" +
				"nuary 1970 00:00:00.000 UTC.\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"" +
				"name\":\"location\",\"doc\":\"Location of this item\",\"default\":null,\"type\":[\"null\",{\"t" +
				"ype\":\"record\",\"name\":\"Location\",\"namespace\":\"eu.driver.model.sim.geo\",\"fields\":[" +
				"{\"name\":\"latitude\",\"doc\":\"Latitude in degrees (-90, 90] - 0 is equator\",\"type\":\"" +
				"double\"},{\"name\":\"longitude\",\"doc\":\"Longitude in degrees (-180, 180] - 0 is line" +
				" [geographic north - Greenwich - geographic south]\",\"type\":\"double\"},{\"name\":\"al" +
				"titude\",\"doc\":\"Altitude in meters - 0 is surface of WGS84-based ellipsoid\",\"defa" +
				"ult\":null,\"type\":[\"null\",\"double\"]}]}]}]}");
		/// <summary>
		/// Globally unique identifier for this post
		/// </summary>
		private string _guid;
		/// <summary>
		/// Name of this post
		/// </summary>
		private string _name;
		/// <summary>
		/// Identifier of the simulator currently responsible for this post
		/// </summary>
		private string _owner;
		/// <summary>
		/// Type of crisis media medium this post was placed on/in
		/// </summary>
		private eu.driver.model.sim.entity.post.MediumTypes _mediumType;
		/// <summary>
		/// Name of the medium this post was placed on/in
		/// </summary>
		private string _mediumName;
		/// <summary>
		/// Title of this post
		/// </summary>
		private string _header;
		/// <summary>
		/// Introduction of this post
		/// </summary>
		private string _intro;
		/// <summary>
		/// The body text of this post
		/// </summary>
		private string _body;
		/// <summary>
		/// Links to files attached to this post
		/// </summary>
		private IList<System.String> _files;
		/// <summary>
		/// Indication whether or not this post is visible for any participant
		/// </summary>
		private bool _visibleForParticipant;
		/// <summary>
		/// Name of the sender sending this post
		/// </summary>
		private string _senderName;
		/// <summary>
		/// Reference to the role sending this post
		/// </summary>
		private string _senderRole;
		/// <summary>
		/// List of references to the roles that should receive this post personally
		/// </summary>
		private IList<System.String> _recipients;
		/// <summary>
		/// The fictive creation date and time of this post as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC.
		/// </summary>
		private long _date;
		/// <summary>
		/// Location of this item
		/// </summary>
		private eu.driver.model.sim.geo.Location _location;
		public virtual Schema Schema
		{
			get
			{
				return Post._SCHEMA;
			}
		}
		/// <summary>
		/// Globally unique identifier for this post
		/// </summary>
		public string guid
		{
			get
			{
				return this._guid;
			}
			set
			{
				this._guid = value;
			}
		}
		/// <summary>
		/// Name of this post
		/// </summary>
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		/// <summary>
		/// Identifier of the simulator currently responsible for this post
		/// </summary>
		public string owner
		{
			get
			{
				return this._owner;
			}
			set
			{
				this._owner = value;
			}
		}
		/// <summary>
		/// Type of crisis media medium this post was placed on/in
		/// </summary>
		public eu.driver.model.sim.entity.post.MediumTypes mediumType
		{
			get
			{
				return this._mediumType;
			}
			set
			{
				this._mediumType = value;
			}
		}
		/// <summary>
		/// Name of the medium this post was placed on/in
		/// </summary>
		public string mediumName
		{
			get
			{
				return this._mediumName;
			}
			set
			{
				this._mediumName = value;
			}
		}
		/// <summary>
		/// Title of this post
		/// </summary>
		public string header
		{
			get
			{
				return this._header;
			}
			set
			{
				this._header = value;
			}
		}
		/// <summary>
		/// Introduction of this post
		/// </summary>
		public string intro
		{
			get
			{
				return this._intro;
			}
			set
			{
				this._intro = value;
			}
		}
		/// <summary>
		/// The body text of this post
		/// </summary>
		public string body
		{
			get
			{
				return this._body;
			}
			set
			{
				this._body = value;
			}
		}
		/// <summary>
		/// Links to files attached to this post
		/// </summary>
		public IList<System.String> files
		{
			get
			{
				return this._files;
			}
			set
			{
				this._files = value;
			}
		}
		/// <summary>
		/// Indication whether or not this post is visible for any participant
		/// </summary>
		public bool visibleForParticipant
		{
			get
			{
				return this._visibleForParticipant;
			}
			set
			{
				this._visibleForParticipant = value;
			}
		}
		/// <summary>
		/// Name of the sender sending this post
		/// </summary>
		public string senderName
		{
			get
			{
				return this._senderName;
			}
			set
			{
				this._senderName = value;
			}
		}
		/// <summary>
		/// Reference to the role sending this post
		/// </summary>
		public string senderRole
		{
			get
			{
				return this._senderRole;
			}
			set
			{
				this._senderRole = value;
			}
		}
		/// <summary>
		/// List of references to the roles that should receive this post personally
		/// </summary>
		public IList<System.String> recipients
		{
			get
			{
				return this._recipients;
			}
			set
			{
				this._recipients = value;
			}
		}
		/// <summary>
		/// The fictive creation date and time of this post as the number of milliseconds from the unix epoch, 1 January 1970 00:00:00.000 UTC.
		/// </summary>
		public long date
		{
			get
			{
				return this._date;
			}
			set
			{
				this._date = value;
			}
		}
		/// <summary>
		/// Location of this item
		/// </summary>
		public eu.driver.model.sim.geo.Location location
		{
			get
			{
				return this._location;
			}
			set
			{
				this._location = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.guid;
			case 1: return this.name;
			case 2: return this.owner;
			case 3: return this.mediumType;
			case 4: return this.mediumName;
			case 5: return this.header;
			case 6: return this.intro;
			case 7: return this.body;
			case 8: return this.files;
			case 9: return this.visibleForParticipant;
			case 10: return this.senderName;
			case 11: return this.senderRole;
			case 12: return this.recipients;
			case 13: return this.date;
			case 14: return this.location;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.guid = (System.String)fieldValue; break;
			case 1: this.name = (System.String)fieldValue; break;
			case 2: this.owner = (System.String)fieldValue; break;
			case 3: this.mediumType = (eu.driver.model.sim.entity.post.MediumTypes)fieldValue; break;
			case 4: this.mediumName = (System.String)fieldValue; break;
			case 5: this.header = (System.String)fieldValue; break;
			case 6: this.intro = (System.String)fieldValue; break;
			case 7: this.body = (System.String)fieldValue; break;
			case 8: this.files = (IList<System.String>)fieldValue; break;
			case 9: this.visibleForParticipant = (System.Boolean)fieldValue; break;
			case 10: this.senderName = (System.String)fieldValue; break;
			case 11: this.senderRole = (System.String)fieldValue; break;
			case 12: this.recipients = (IList<System.String>)fieldValue; break;
			case 13: this.date = (System.Int64)fieldValue; break;
			case 14: this.location = (eu.driver.model.sim.geo.Location)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
