// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.core
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Log : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Log\",\"namespace\":\"eu.driver.model.core\",\"fields\":[{\"name" +
				"\":\"id\",\"doc\":\"Client id\",\"type\":\"string\"},{\"name\":\"log\",\"doc\":\"Actual log messag" +
				"e\",\"type\":\"string\"}]}");
		/// <summary>
		/// Client id
		/// </summary>
		private string _id;
		/// <summary>
		/// Actual log message
		/// </summary>
		private string _log;
		public virtual Schema Schema
		{
			get
			{
				return Log._SCHEMA;
			}
		}
		/// <summary>
		/// Client id
		/// </summary>
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		/// <summary>
		/// Actual log message
		/// </summary>
		public string log
		{
			get
			{
				return this._log;
			}
			set
			{
				this._log = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.log;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.String)fieldValue; break;
			case 1: this.log = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
