// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.geojson
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class GeoJSONEnvelope : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"GeoJSONEnvelope\",\"namespace\":\"eu.driver.model.geojson\",\"" +
				"fields\":[{\"name\":\"properties\",\"doc\":\"Metadata for the FeatureCollection in the g" +
				"eojson field.\",\"type\":[\"null\",{\"type\":\"map\",\"values\":[\"null\",\"boolean\",\"string\"," +
				"\"int\",\"long\",\"float\",\"double\"]}]},{\"name\":\"geojson\",\"type\":{\"type\":\"record\",\"nam" +
				"e\":\"FeatureCollection\",\"namespace\":\"eu.driver.model.geojson\",\"fields\":[{\"name\":\"" +
				"type\",\"default\":\"FeatureCollection\",\"type\":{\"type\":\"enum\",\"name\":\"FeatureCollect" +
				"ionType\",\"namespace\":\"eu.driver.model.geojson\",\"symbols\":[\"FeatureCollection\"]}}" +
				",{\"name\":\"bbox\",\"default\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":\"double\"}]" +
				"},{\"name\":\"features\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"na" +
				"me\":\"Feature\",\"namespace\":\"eu.driver.model.geojson\",\"fields\":[{\"name\":\"type\",\"de" +
				"fault\":\"Feature\",\"type\":{\"type\":\"enum\",\"name\":\"FeatureType\",\"namespace\":\"eu.driv" +
				"er.model.geojson\",\"symbols\":[\"Feature\"]}},{\"name\":\"bbox\",\"default\":null,\"type\":[" +
				"\"null\",{\"type\":\"array\",\"items\":\"double\"}]},{\"name\":\"geometry\",\"type\":[{\"type\":\"r" +
				"ecord\",\"name\":\"Point\",\"namespace\":\"eu.driver.model.geojson\",\"fields\":[{\"name\":\"t" +
				"ype\",\"default\":\"Point\",\"type\":{\"type\":\"enum\",\"name\":\"PointType\",\"namespace\":\"eu." +
				"driver.model.geojson\",\"symbols\":[\"Point\"]}},{\"name\":\"coordinates\",\"type\":{\"type\"" +
				":\"array\",\"items\":\"double\"}}]},{\"type\":\"record\",\"name\":\"LineString\",\"namespace\":\"" +
				"eu.driver.model.geojson\",\"fields\":[{\"name\":\"type\",\"default\":\"LineString\",\"type\":" +
				"{\"type\":\"enum\",\"name\":\"LineStringType\",\"namespace\":\"eu.driver.model.geojson\",\"sy" +
				"mbols\":[\"LineString\"]}},{\"name\":\"coordinates\",\"type\":{\"type\":\"array\",\"items\":{\"t" +
				"ype\":\"array\",\"items\":\"double\"}}}]},{\"type\":\"record\",\"name\":\"MultiLineString\",\"na" +
				"mespace\":\"eu.driver.model.geojson\",\"fields\":[{\"name\":\"type\",\"default\":\"MultiLine" +
				"String\",\"type\":{\"type\":\"enum\",\"name\":\"MultiLineStringType\",\"namespace\":\"eu.drive" +
				"r.model.geojson\",\"symbols\":[\"MultiLineString\"]}},{\"name\":\"coordinates\",\"type\":{\"" +
				"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":\"double\"}}" +
				"}}]},{\"type\":\"record\",\"name\":\"Polygon\",\"namespace\":\"eu.driver.model.geojson\",\"fi" +
				"elds\":[{\"name\":\"type\",\"default\":\"Polygon\",\"type\":{\"type\":\"enum\",\"name\":\"PolygonT" +
				"ype\",\"namespace\":\"eu.driver.model.geojson\",\"symbols\":[\"Polygon\"]}},{\"name\":\"coor" +
				"dinates\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":{\"type\":\"array\"," +
				"\"items\":\"double\"}}}}]},{\"type\":\"record\",\"name\":\"MultiPolygon\",\"namespace\":\"eu.dr" +
				"iver.model.geojson\",\"fields\":[{\"name\":\"type\",\"default\":\"MultiPolygon\",\"type\":{\"t" +
				"ype\":\"enum\",\"name\":\"MultiPolygonType\",\"namespace\":\"eu.driver.model.geojson\",\"sym" +
				"bols\":[\"MultiPolygon\"]}},{\"name\":\"coordinates\",\"type\":{\"type\":\"array\",\"items\":{\"" +
				"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":\"double\"}}" +
				"}}}]}]},{\"name\":\"properties\",\"doc\":\"Any type, without infinite nesting, should b" +
				"e replaced during actual usage with a record with named properties.\",\"type\":{\"ty" +
				"pe\":\"map\",\"values\":[\"null\",\"boolean\",\"string\",\"int\",\"long\",\"float\",\"double\",{\"ty" +
				"pe\":\"array\",\"items\":[\"null\",\"boolean\",\"string\",\"int\",\"long\",\"float\",\"double\"]},{" +
				"\"type\":\"map\",\"values\":[\"null\",\"boolean\",\"string\",\"int\",\"long\",\"float\",\"double\"]}" +
				"]}}]}}]}]}}]}");
		/// <summary>
		/// Metadata for the FeatureCollection in the geojson field.
		/// </summary>
		private IDictionary<string,System.Object> _properties;
		private eu.driver.model.geojson.FeatureCollection _geojson;
		public virtual Schema Schema
		{
			get
			{
				return GeoJSONEnvelope._SCHEMA;
			}
		}
		/// <summary>
		/// Metadata for the FeatureCollection in the geojson field.
		/// </summary>
		public IDictionary<string,System.Object> properties
		{
			get
			{
				return this._properties;
			}
			set
			{
				this._properties = value;
			}
		}
		public eu.driver.model.geojson.FeatureCollection geojson
		{
			get
			{
				return this._geojson;
			}
			set
			{
				this._geojson = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.properties;
			case 1: return this.geojson;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.properties = (IDictionary<string,System.Object>)fieldValue; break;
			case 1: this.geojson = (eu.driver.model.geojson.FeatureCollection)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
