// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.geojson.photo
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class properties : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"properties\",\"namespace\":\"eu.driver.model.geojson.photo\"," +
				"\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"priority\",\"type\":\"long\"},{\"name\":" +
				"\"viewed\",\"type\":\"boolean\"},{\"name\":\"signature\",\"type\":\"string\"},{\"name\":\"instant" +
				"\",\"type\":\"string\"},{\"name\":\"created\",\"type\":[\"null\",\"string\"]},{\"name\":\"updated\"" +
				",\"type\":\"string\"},{\"name\":\"caption\",\"type\":[\"null\",\"string\"]},{\"name\":\"interpret" +
				"ation\",\"type\":[\"string\",\"null\"]},{\"name\":\"meta\",\"type\":{\"type\":\"record\",\"name\":\"" +
				"meta\",\"namespace\":\"eu.driver.model.geojson.photo\",\"fields\":[{\"name\":\"Source\",\"ty" +
				"pe\":{\"type\":\"record\",\"name\":\"Source\",\"namespace\":\"eu.driver.model.geojson.photo\"" +
				",\"fields\":[{\"name\":\"filename\",\"type\":\"string\"},{\"name\":\"camera_make\",\"type\":[\"nu" +
				"ll\",\"string\"]},{\"name\":\"width\",\"type\":\"long\"},{\"name\":\"size\",\"type\":\"long\"},{\"na" +
				"me\":\"height\",\"type\":\"long\"},{\"name\":\"direction\",\"type\":[\"null\",\"double\"]},{\"name" +
				"\":\"camera_model\",\"type\":[\"null\",\"string\"]},{\"name\":\"field_of_view\",\"type\":[\"null" +
				"\",\"double\"]}]}}]}},{\"name\":\"version\",\"type\":[\"string\",\"null\"]},{\"name\":\"applicat" +
				"ion_id\",\"type\":[\"string\",\"null\"]},{\"name\":\"seen\",\"type\":[\"string\",\"null\"]},{\"nam" +
				"e\":\"started\",\"type\":[\"string\",\"null\"]},{\"name\":\"stopped\",\"type\":[\"string\",\"null\"" +
				"]},{\"name\":\"location_latitude\",\"type\":\"double\"},{\"name\":\"location_longitude\",\"ty" +
				"pe\":\"double\"},{\"name\":\"location_time\",\"type\":\"string\"},{\"name\":\"location_accurac" +
				"y\",\"type\":[\"double\",\"null\"]},{\"name\":\"location_altitude\",\"type\":[\"double\",\"null\"" +
				"]},{\"name\":\"location_provider\",\"type\":[\"string\",\"null\"]},{\"name\":\"location_speed" +
				"\",\"type\":[\"double\",\"null\"]},{\"name\":\"location_meta\",\"type\":[\"string\",\"null\"]},{\"" +
				"name\":\"mission_id\",\"type\":[\"long\",\"null\"]},{\"name\":\"mission_name\",\"type\":[\"strin" +
				"g\",\"null\"]},{\"name\":\"thumbnail_hash\",\"type\":\"string\"},{\"name\":\"preview_hash\",\"ty" +
				"pe\":\"string\"},{\"name\":\"category_id\",\"type\":[\"long\",\"null\"]},{\"name\":\"category_na" +
				"me\",\"type\":[\"string\",\"null\"]},{\"name\":\"application_device_type\",\"type\":[\"int\",\"n" +
				"ull\"]},{\"name\":\"application_last_login\",\"type\":[\"string\",\"null\"]},{\"name\":\"appli" +
				"cation_phone\",\"type\":[\"string\",\"null\"]},{\"name\":\"application_last_rate\",\"type\":[" +
				"\"long\",\"null\"]},{\"name\":\"application_updated\",\"type\":[\"string\",\"null\"]},{\"name\":" +
				"\"application_created\",\"type\":[\"string\",\"null\"]},{\"name\":\"application_application" +
				"_type\",\"type\":[\"int\",\"null\"]},{\"name\":\"application_connection_type\",\"type\":[\"int" +
				"\",\"null\"]},{\"name\":\"application_connection_state\",\"type\":[\"int\",\"null\"]},{\"name\"" +
				":\"user_name\",\"type\":\"string\"},{\"name\":\"user_id\",\"type\":\"long\"},{\"name\":\"user_use" +
				"rname\",\"type\":\"string\"},{\"name\":\"user_color\",\"type\":[\"string\",\"null\"]},{\"name\":\"" +
				"user_connection_type\",\"type\":[\"int\",\"null\"]},{\"name\":\"user_last_login\",\"type\":[\"" +
				"string\",\"null\"]},{\"name\":\"user_last_rate\",\"type\":[\"long\",\"null\"]},{\"name\":\"obser" +
				"vation_url\",\"type\":\"string\"},{\"name\":\"observation_type\",\"type\":\"string\"},{\"name\"" +
				":\"preview_url\",\"type\":\"string\"},{\"name\":\"preview_with_overlay_url\",\"type\":\"strin" +
				"g\"},{\"name\":\"thumbnail_url\",\"type\":\"string\"},{\"name\":\"files\",\"type\":{\"type\":\"arr" +
				"ay\",\"items\":{\"type\":\"record\",\"name\":\"files\",\"namespace\":\"eu.driver.model.geojson" +
				".photo.files\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"file_type\",\"type\":\"" +
				"int\"},{\"name\":\"size\",\"type\":[\"long\",\"null\"]},{\"name\":\"state\",\"type\":\"int\"},{\"nam" +
				"e\":\"created\",\"type\":\"string\"},{\"name\":\"request_until\",\"default\":null,\"type\":[\"nu" +
				"ll\",\"string\"]},{\"name\":\"meta\",\"type\":[\"null\",\"string\",{\"type\":\"record\",\"name\":\"m" +
				"eta\",\"namespace\":\"eu.driver.model.geojson.photo.files\",\"fields\":[{\"name\":\"Region" +
				"\",\"type\":{\"type\":\"record\",\"name\":\"Region\",\"namespace\":\"eu.driver.model.geojson.p" +
				"hoto.files\",\"fields\":[{\"name\":\"x\",\"type\":\"long\"},{\"name\":\"y\",\"type\":\"long\"},{\"na" +
				"me\":\"width\",\"type\":\"long\"},{\"name\":\"height\",\"type\":\"long\"},{\"name\":\"scale\",\"type" +
				"\":\"double\"},{\"name\":\"quality\",\"type\":\"int\"}]}}]}]},{\"name\":\"hash\",\"type\":[\"null\"" +
				",\"string\"]},{\"name\":\"url\",\"type\":[\"null\",\"string\"]}]}}}]}");
		private long _id;
		private long _priority;
		private bool _viewed;
		private string _signature;
		private string _instant;
		private string _created;
		private string _updated;
		private string _caption;
		private string _interpretation;
		private eu.driver.model.geojson.photo.meta _meta;
		private string _version;
		private string _application_id;
		private string _seen;
		private string _started;
		private string _stopped;
		private double _location_latitude;
		private double _location_longitude;
		private string _location_time;
		private System.Nullable<double> _location_accuracy;
		private System.Nullable<double> _location_altitude;
		private string _location_provider;
		private System.Nullable<double> _location_speed;
		private string _location_meta;
		private System.Nullable<long> _mission_id;
		private string _mission_name;
		private string _thumbnail_hash;
		private string _preview_hash;
		private System.Nullable<long> _category_id;
		private string _category_name;
		private System.Nullable<int> _application_device_type;
		private string _application_last_login;
		private string _application_phone;
		private System.Nullable<long> _application_last_rate;
		private string _application_updated;
		private string _application_created;
		private System.Nullable<int> _application_application_type;
		private System.Nullable<int> _application_connection_type;
		private System.Nullable<int> _application_connection_state;
		private string _user_name;
		private long _user_id;
		private string _user_username;
		private string _user_color;
		private System.Nullable<int> _user_connection_type;
		private string _user_last_login;
		private System.Nullable<long> _user_last_rate;
		private string _observation_url;
		private string _observation_type;
		private string _preview_url;
		private string _preview_with_overlay_url;
		private string _thumbnail_url;
		private IList<eu.driver.model.geojson.photo.files.files> _files;
		public virtual Schema Schema
		{
			get
			{
				return properties._SCHEMA;
			}
		}
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public long priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				this._priority = value;
			}
		}
		public bool viewed
		{
			get
			{
				return this._viewed;
			}
			set
			{
				this._viewed = value;
			}
		}
		public string signature
		{
			get
			{
				return this._signature;
			}
			set
			{
				this._signature = value;
			}
		}
		public string instant
		{
			get
			{
				return this._instant;
			}
			set
			{
				this._instant = value;
			}
		}
		public string created
		{
			get
			{
				return this._created;
			}
			set
			{
				this._created = value;
			}
		}
		public string updated
		{
			get
			{
				return this._updated;
			}
			set
			{
				this._updated = value;
			}
		}
		public string caption
		{
			get
			{
				return this._caption;
			}
			set
			{
				this._caption = value;
			}
		}
		public string interpretation
		{
			get
			{
				return this._interpretation;
			}
			set
			{
				this._interpretation = value;
			}
		}
		public eu.driver.model.geojson.photo.meta meta
		{
			get
			{
				return this._meta;
			}
			set
			{
				this._meta = value;
			}
		}
		public string version
		{
			get
			{
				return this._version;
			}
			set
			{
				this._version = value;
			}
		}
		public string application_id
		{
			get
			{
				return this._application_id;
			}
			set
			{
				this._application_id = value;
			}
		}
		public string seen
		{
			get
			{
				return this._seen;
			}
			set
			{
				this._seen = value;
			}
		}
		public string started
		{
			get
			{
				return this._started;
			}
			set
			{
				this._started = value;
			}
		}
		public string stopped
		{
			get
			{
				return this._stopped;
			}
			set
			{
				this._stopped = value;
			}
		}
		public double location_latitude
		{
			get
			{
				return this._location_latitude;
			}
			set
			{
				this._location_latitude = value;
			}
		}
		public double location_longitude
		{
			get
			{
				return this._location_longitude;
			}
			set
			{
				this._location_longitude = value;
			}
		}
		public string location_time
		{
			get
			{
				return this._location_time;
			}
			set
			{
				this._location_time = value;
			}
		}
		public System.Nullable<double> location_accuracy
		{
			get
			{
				return this._location_accuracy;
			}
			set
			{
				this._location_accuracy = value;
			}
		}
		public System.Nullable<double> location_altitude
		{
			get
			{
				return this._location_altitude;
			}
			set
			{
				this._location_altitude = value;
			}
		}
		public string location_provider
		{
			get
			{
				return this._location_provider;
			}
			set
			{
				this._location_provider = value;
			}
		}
		public System.Nullable<double> location_speed
		{
			get
			{
				return this._location_speed;
			}
			set
			{
				this._location_speed = value;
			}
		}
		public string location_meta
		{
			get
			{
				return this._location_meta;
			}
			set
			{
				this._location_meta = value;
			}
		}
		public System.Nullable<long> mission_id
		{
			get
			{
				return this._mission_id;
			}
			set
			{
				this._mission_id = value;
			}
		}
		public string mission_name
		{
			get
			{
				return this._mission_name;
			}
			set
			{
				this._mission_name = value;
			}
		}
		public string thumbnail_hash
		{
			get
			{
				return this._thumbnail_hash;
			}
			set
			{
				this._thumbnail_hash = value;
			}
		}
		public string preview_hash
		{
			get
			{
				return this._preview_hash;
			}
			set
			{
				this._preview_hash = value;
			}
		}
		public System.Nullable<long> category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				this._category_id = value;
			}
		}
		public string category_name
		{
			get
			{
				return this._category_name;
			}
			set
			{
				this._category_name = value;
			}
		}
		public System.Nullable<int> application_device_type
		{
			get
			{
				return this._application_device_type;
			}
			set
			{
				this._application_device_type = value;
			}
		}
		public string application_last_login
		{
			get
			{
				return this._application_last_login;
			}
			set
			{
				this._application_last_login = value;
			}
		}
		public string application_phone
		{
			get
			{
				return this._application_phone;
			}
			set
			{
				this._application_phone = value;
			}
		}
		public System.Nullable<long> application_last_rate
		{
			get
			{
				return this._application_last_rate;
			}
			set
			{
				this._application_last_rate = value;
			}
		}
		public string application_updated
		{
			get
			{
				return this._application_updated;
			}
			set
			{
				this._application_updated = value;
			}
		}
		public string application_created
		{
			get
			{
				return this._application_created;
			}
			set
			{
				this._application_created = value;
			}
		}
		public System.Nullable<int> application_application_type
		{
			get
			{
				return this._application_application_type;
			}
			set
			{
				this._application_application_type = value;
			}
		}
		public System.Nullable<int> application_connection_type
		{
			get
			{
				return this._application_connection_type;
			}
			set
			{
				this._application_connection_type = value;
			}
		}
		public System.Nullable<int> application_connection_state
		{
			get
			{
				return this._application_connection_state;
			}
			set
			{
				this._application_connection_state = value;
			}
		}
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				this._user_name = value;
			}
		}
		public long user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				this._user_id = value;
			}
		}
		public string user_username
		{
			get
			{
				return this._user_username;
			}
			set
			{
				this._user_username = value;
			}
		}
		public string user_color
		{
			get
			{
				return this._user_color;
			}
			set
			{
				this._user_color = value;
			}
		}
		public System.Nullable<int> user_connection_type
		{
			get
			{
				return this._user_connection_type;
			}
			set
			{
				this._user_connection_type = value;
			}
		}
		public string user_last_login
		{
			get
			{
				return this._user_last_login;
			}
			set
			{
				this._user_last_login = value;
			}
		}
		public System.Nullable<long> user_last_rate
		{
			get
			{
				return this._user_last_rate;
			}
			set
			{
				this._user_last_rate = value;
			}
		}
		public string observation_url
		{
			get
			{
				return this._observation_url;
			}
			set
			{
				this._observation_url = value;
			}
		}
		public string observation_type
		{
			get
			{
				return this._observation_type;
			}
			set
			{
				this._observation_type = value;
			}
		}
		public string preview_url
		{
			get
			{
				return this._preview_url;
			}
			set
			{
				this._preview_url = value;
			}
		}
		public string preview_with_overlay_url
		{
			get
			{
				return this._preview_with_overlay_url;
			}
			set
			{
				this._preview_with_overlay_url = value;
			}
		}
		public string thumbnail_url
		{
			get
			{
				return this._thumbnail_url;
			}
			set
			{
				this._thumbnail_url = value;
			}
		}
		public IList<eu.driver.model.geojson.photo.files.files> files
		{
			get
			{
				return this._files;
			}
			set
			{
				this._files = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.priority;
			case 2: return this.viewed;
			case 3: return this.signature;
			case 4: return this.instant;
			case 5: return this.created;
			case 6: return this.updated;
			case 7: return this.caption;
			case 8: return this.interpretation;
			case 9: return this.meta;
			case 10: return this.version;
			case 11: return this.application_id;
			case 12: return this.seen;
			case 13: return this.started;
			case 14: return this.stopped;
			case 15: return this.location_latitude;
			case 16: return this.location_longitude;
			case 17: return this.location_time;
			case 18: return this.location_accuracy;
			case 19: return this.location_altitude;
			case 20: return this.location_provider;
			case 21: return this.location_speed;
			case 22: return this.location_meta;
			case 23: return this.mission_id;
			case 24: return this.mission_name;
			case 25: return this.thumbnail_hash;
			case 26: return this.preview_hash;
			case 27: return this.category_id;
			case 28: return this.category_name;
			case 29: return this.application_device_type;
			case 30: return this.application_last_login;
			case 31: return this.application_phone;
			case 32: return this.application_last_rate;
			case 33: return this.application_updated;
			case 34: return this.application_created;
			case 35: return this.application_application_type;
			case 36: return this.application_connection_type;
			case 37: return this.application_connection_state;
			case 38: return this.user_name;
			case 39: return this.user_id;
			case 40: return this.user_username;
			case 41: return this.user_color;
			case 42: return this.user_connection_type;
			case 43: return this.user_last_login;
			case 44: return this.user_last_rate;
			case 45: return this.observation_url;
			case 46: return this.observation_type;
			case 47: return this.preview_url;
			case 48: return this.preview_with_overlay_url;
			case 49: return this.thumbnail_url;
			case 50: return this.files;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.Int64)fieldValue; break;
			case 1: this.priority = (System.Int64)fieldValue; break;
			case 2: this.viewed = (System.Boolean)fieldValue; break;
			case 3: this.signature = (System.String)fieldValue; break;
			case 4: this.instant = (System.String)fieldValue; break;
			case 5: this.created = (System.String)fieldValue; break;
			case 6: this.updated = (System.String)fieldValue; break;
			case 7: this.caption = (System.String)fieldValue; break;
			case 8: this.interpretation = (System.String)fieldValue; break;
			case 9: this.meta = (eu.driver.model.geojson.photo.meta)fieldValue; break;
			case 10: this.version = (System.String)fieldValue; break;
			case 11: this.application_id = (System.String)fieldValue; break;
			case 12: this.seen = (System.String)fieldValue; break;
			case 13: this.started = (System.String)fieldValue; break;
			case 14: this.stopped = (System.String)fieldValue; break;
			case 15: this.location_latitude = (System.Double)fieldValue; break;
			case 16: this.location_longitude = (System.Double)fieldValue; break;
			case 17: this.location_time = (System.String)fieldValue; break;
			case 18: this.location_accuracy = (System.Nullable<double>)fieldValue; break;
			case 19: this.location_altitude = (System.Nullable<double>)fieldValue; break;
			case 20: this.location_provider = (System.String)fieldValue; break;
			case 21: this.location_speed = (System.Nullable<double>)fieldValue; break;
			case 22: this.location_meta = (System.String)fieldValue; break;
			case 23: this.mission_id = (System.Nullable<long>)fieldValue; break;
			case 24: this.mission_name = (System.String)fieldValue; break;
			case 25: this.thumbnail_hash = (System.String)fieldValue; break;
			case 26: this.preview_hash = (System.String)fieldValue; break;
			case 27: this.category_id = (System.Nullable<long>)fieldValue; break;
			case 28: this.category_name = (System.String)fieldValue; break;
			case 29: this.application_device_type = (System.Nullable<int>)fieldValue; break;
			case 30: this.application_last_login = (System.String)fieldValue; break;
			case 31: this.application_phone = (System.String)fieldValue; break;
			case 32: this.application_last_rate = (System.Nullable<long>)fieldValue; break;
			case 33: this.application_updated = (System.String)fieldValue; break;
			case 34: this.application_created = (System.String)fieldValue; break;
			case 35: this.application_application_type = (System.Nullable<int>)fieldValue; break;
			case 36: this.application_connection_type = (System.Nullable<int>)fieldValue; break;
			case 37: this.application_connection_state = (System.Nullable<int>)fieldValue; break;
			case 38: this.user_name = (System.String)fieldValue; break;
			case 39: this.user_id = (System.Int64)fieldValue; break;
			case 40: this.user_username = (System.String)fieldValue; break;
			case 41: this.user_color = (System.String)fieldValue; break;
			case 42: this.user_connection_type = (System.Nullable<int>)fieldValue; break;
			case 43: this.user_last_login = (System.String)fieldValue; break;
			case 44: this.user_last_rate = (System.Nullable<long>)fieldValue; break;
			case 45: this.observation_url = (System.String)fieldValue; break;
			case 46: this.observation_type = (System.String)fieldValue; break;
			case 47: this.preview_url = (System.String)fieldValue; break;
			case 48: this.preview_with_overlay_url = (System.String)fieldValue; break;
			case 49: this.thumbnail_url = (System.String)fieldValue; break;
			case 50: this.files = (IList<eu.driver.model.geojson.photo.files.files>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
