// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.geojson.sim
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class FeatureCollection : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"FeatureCollection\",\"namespace\":\"eu.driver.model.geojson." +
				"sim\",\"fields\":[{\"name\":\"type\",\"default\":\"FeatureCollection\",\"type\":{\"type\":\"enum" +
				"\",\"name\":\"FeatureCollectionType\",\"namespace\":\"eu.driver.model.geojson.sim\",\"symb" +
				"ols\":[\"FeatureCollection\"]}},{\"name\":\"bbox\",\"default\":null,\"type\":[\"null\",{\"type" +
				"\":\"array\",\"items\":\"double\"}]},{\"name\":\"features\",\"type\":[\"null\",{\"type\":\"array\"," +
				"\"items\":{\"type\":\"record\",\"name\":\"Feature\",\"namespace\":\"eu.driver.model.geojson.s" +
				"im\",\"fields\":[{\"name\":\"type\",\"default\":\"Feature\",\"type\":{\"type\":\"enum\",\"name\":\"F" +
				"eatureType\",\"namespace\":\"eu.driver.model.geojson.sim\",\"symbols\":[\"Feature\"]}},{\"" +
				"name\":\"bbox\",\"default\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":\"double\"}]},{" +
				"\"name\":\"geometry\",\"type\":[{\"type\":\"record\",\"name\":\"Point\",\"namespace\":\"eu.driver" +
				".model.geojson.sim\",\"fields\":[{\"name\":\"type\",\"default\":\"Point\",\"type\":{\"type\":\"e" +
				"num\",\"name\":\"PointType\",\"namespace\":\"eu.driver.model.geojson.sim\",\"symbols\":[\"Po" +
				"int\"]}},{\"name\":\"coordinates\",\"type\":{\"type\":\"array\",\"items\":\"double\"}}]},{\"type" +
				"\":\"record\",\"name\":\"LineString\",\"namespace\":\"eu.driver.model.geojson.sim\",\"fields" +
				"\":[{\"name\":\"type\",\"default\":\"LineString\",\"type\":{\"type\":\"enum\",\"name\":\"LineStrin" +
				"gType\",\"namespace\":\"eu.driver.model.geojson.sim\",\"symbols\":[\"LineString\"]}},{\"na" +
				"me\":\"coordinates\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":\"double" +
				"\"}}}]},{\"type\":\"record\",\"name\":\"MultiLineString\",\"namespace\":\"eu.driver.model.ge" +
				"ojson.sim\",\"fields\":[{\"name\":\"type\",\"default\":\"MultiLineString\",\"type\":{\"type\":\"" +
				"enum\",\"name\":\"MultiLineStringType\",\"namespace\":\"eu.driver.model.geojson.sim\",\"sy" +
				"mbols\":[\"MultiLineString\"]}},{\"name\":\"coordinates\",\"type\":{\"type\":\"array\",\"items" +
				"\":{\"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":\"double\"}}}}]},{\"type\":\"record" +
				"\",\"name\":\"Polygon\",\"namespace\":\"eu.driver.model.geojson.sim\",\"fields\":[{\"name\":\"" +
				"type\",\"default\":\"Polygon\",\"type\":{\"type\":\"enum\",\"name\":\"PolygonType\",\"namespace\"" +
				":\"eu.driver.model.geojson.sim\",\"symbols\":[\"Polygon\"]}},{\"name\":\"coordinates\",\"ty" +
				"pe\":{\"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":\"dou" +
				"ble\"}}}}]},{\"type\":\"record\",\"name\":\"MultiPolygon\",\"namespace\":\"eu.driver.model.g" +
				"eojson.sim\",\"fields\":[{\"name\":\"type\",\"default\":\"MultiPolygon\",\"type\":{\"type\":\"en" +
				"um\",\"name\":\"MultiPolygonType\",\"namespace\":\"eu.driver.model.geojson.sim\",\"symbols" +
				"\":[\"MultiPolygon\"]}},{\"name\":\"coordinates\",\"type\":{\"type\":\"array\",\"items\":{\"type" +
				"\":\"array\",\"items\":{\"type\":\"array\",\"items\":{\"type\":\"array\",\"items\":\"double\"}}}}}]" +
				"}]},{\"name\":\"properties\",\"doc\":\"Properties that provide additional specification" +
				" of the Simulated entity in addition to its geographic information.\",\"type\":{\"ty" +
				"pe\":\"record\",\"name\":\"SimulatedEntityProperties\",\"namespace\":\"eu.driver.model.geo" +
				"json.sim\",\"fields\":[{\"name\":\"guid\",\"doc\":\"globally unique identifier for this en" +
				"tity\",\"type\":\"string\"},{\"name\":\"name\",\"doc\":\"name of this entity\",\"type\":\"string" +
				"\"},{\"name\":\"speed\",\"doc\":\"speed of the entity in m/s\",\"default\":null,\"type\":[\"nu" +
				"ll\",\"double\"]},{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"TypeEnum\",\"namespace" +
				"\":\"eu.driver.model.geojson.sim\",\"symbols\":[\"OBJECT\",\"PERSON\",\"CAR\",\"VAN\",\"TRUCK\"" +
				",\"BOAT\",\"PLANE\",\"HELICOPTER\",\"MOTORCYCLE\",\"DRONE\",\"UNIT\",\"STATION\",\"UNITGROUP\",\"" +
				"UNKNOWN\"]}},{\"name\":\"label\",\"doc\":\"Label that describes the domain of the entity" +
				". E.g. Police, Medical, Fire or Military.\",\"type\":\"string\"},{\"name\":\"subEntities" +
				"\",\"doc\":\"Entities contained by this entity. Only used for Units, Stations and Un" +
				"it Groups. Array of strings consists of guids.\",\"default\":null,\"type\":[\"null\",{\"" +
				"type\":\"array\",\"items\":\"string\"}]}]}}]}}]}]}");
		private eu.driver.model.geojson.sim.FeatureCollectionType _type;
		private IList<System.Double> _bbox;
		private IList<eu.driver.model.geojson.sim.Feature> _features;
		public virtual Schema Schema
		{
			get
			{
				return FeatureCollection._SCHEMA;
			}
		}
		public eu.driver.model.geojson.sim.FeatureCollectionType type
		{
			get
			{
				return this._type;
			}
			set
			{
				this._type = value;
			}
		}
		public IList<System.Double> bbox
		{
			get
			{
				return this._bbox;
			}
			set
			{
				this._bbox = value;
			}
		}
		public IList<eu.driver.model.geojson.sim.Feature> features
		{
			get
			{
				return this._features;
			}
			set
			{
				this._features = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.type;
			case 1: return this.bbox;
			case 2: return this.features;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.type = (eu.driver.model.geojson.sim.FeatureCollectionType)fieldValue; break;
			case 1: this.bbox = (IList<System.Double>)fieldValue; break;
			case 2: this.features = (IList<eu.driver.model.geojson.sim.Feature>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
