// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.geojson.sim
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public enum TypeEnum
	{
		OBJECT,
		PERSON,
		CAR,
		VAN,
		TRUCK,
		BOAT,
		PLANE,
		HELICOPTER,
		MOTORCYCLE,
		DRONE,
		UNIT,
		STATION,
		UNITGROUP,
		UNKNOWN,
	}
}
