// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.mlp
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Alt : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Alt\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\"" +
				":\"alt\",\"doc\":\"Altitude in meters\",\"type\":\"int\"}]}");
		/// <summary>
		/// Altitude in meters
		/// </summary>
		private int _alt;
		public virtual Schema Schema
		{
			get
			{
				return Alt._SCHEMA;
			}
		}
		/// <summary>
		/// Altitude in meters
		/// </summary>
		public int alt
		{
			get
			{
				return this._alt;
			}
			set
			{
				this._alt = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.alt;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.alt = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
