// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.mlp
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Pos : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Pos\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\"" +
				":\"msid\",\"type\":{\"type\":\"record\",\"name\":\"Msid\",\"namespace\":\"eu.driver.model.mlp\"," +
				"\"fields\":[{\"name\":\"msid\",\"type\":\"string\"},{\"name\":\"attr_type\",\"type\":{\"type\":\"en" +
				"um\",\"name\":\"AttrType\",\"namespace\":\"eu.driver.model.mlp\",\"symbols\":[\"MSISDN\",\"IMS" +
				"I\",\"IMEI\",\"MIN\",\"MDN\",\"EME_MSID\",\"ASID\",\"OPE_ID\",\"IPV4\",\"IPV6\",\"SESSID\"]}},{\"nam" +
				"e\":\"attr_enc\",\"type\":{\"type\":\"enum\",\"name\":\"AttrEnc\",\"namespace\":\"eu.driver.mode" +
				"l.mlp\",\"symbols\":[\"ASC\",\"CRP\"]}}]}},{\"name\":\"pd_poserr\",\"type\":[{\"type\":\"record\"" +
				",\"name\":\"Pd\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"time\",\"type\":{" +
				"\"type\":\"record\",\"name\":\"Time\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name" +
				"\":\"time\",\"doc\":\"UTC Timestamp in milliseconds. Original MLP uses String: yyyyMMd" +
				"dhhmmss\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"attr_utc_off\"," +
				"\"doc\":\"Specifies the UTC [UTC] offset in hours and minutes. Positive values indi" +
				"cate time zones east of Greenwich.\",\"default\":\"0000\",\"type\":\"string\"}]}},{\"name\"" +
				":\"shape\",\"doc\":\"TODO: add  MultiLineString | MultiPoint | MultiPolygon if they a" +
				"re needed\",\"type\":[{\"type\":\"record\",\"name\":\"Point\",\"namespace\":\"eu.driver.model." +
				"mlp\",\"fields\":[{\"name\":\"coord\",\"type\":{\"type\":\"record\",\"name\":\"Coord\",\"namespace" +
				"\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"X\",\"doc\":\"The first coordinate in a c" +
				"oordinate system (30 27 45.3N)\",\"type\":\"string\"},{\"name\":\"Y\",\"doc\":\"Second ordin" +
				"ate in a coordinate.system (45 25 52.9E). This is optional if it is a linear coo" +
				"rdinate system.\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"Z\",\"doc\":\"Thi" +
				"rd ordinate in a coordinate system which has at least three ordinates.\",\"default" +
				"\":null,\"type\":[\"null\",\"double\"]}]}},{\"name\":\"attr_gid\",\"default\":null,\"type\":[\"n" +
				"ull\",\"string\"]},{\"name\":\"attr_srsName\",\"default\":null,\"type\":[\"null\",\"string\"]}]" +
				"},{\"type\":\"record\",\"name\":\"LineString\",\"namespace\":\"eu.driver.model.mlp\",\"fields" +
				"\":[{\"name\":\"coord\",\"doc\":\"Must contain at least 2 coordinates\",\"type\":{\"type\":\"a" +
				"rray\",\"items\":\"Coord\"}},{\"name\":\"attr_gid\",\"default\":null,\"type\":[\"null\",\"string" +
				"\"]},{\"name\":\"attr_srsName\",\"default\":null,\"type\":[\"null\",\"string\"]}]},{\"type\":\"r" +
				"ecord\",\"name\":\"Polygon\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"out" +
				"erBoundaryIs\",\"type\":{\"type\":\"record\",\"name\":\"LinearRing\",\"namespace\":\"eu.driver" +
				".model.mlp\",\"fields\":[{\"name\":\"coords\",\"doc\":\"Must contain at least 3 coordinate" +
				"s\",\"type\":{\"type\":\"array\",\"items\":\"Coord\"}}]}},{\"name\":\"innerBoundaryIs\",\"defaul" +
				"t\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":\"LinearRing\"}]},{\"name\":\"attr_gid" +
				"\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"attr_srsName\",\"default\":null" +
				",\"type\":[\"null\",\"string\"]}]},{\"type\":\"record\",\"name\":\"Box\",\"namespace\":\"eu.drive" +
				"r.model.mlp\",\"fields\":[{\"name\":\"coordTopLeft\",\"type\":\"Coord\"},{\"name\":\"coordBott" +
				"omRight\",\"type\":\"Coord\"},{\"name\":\"attr_gid\",\"default\":null,\"type\":[\"null\",\"strin" +
				"g\"]},{\"name\":\"attr_srsName\",\"default\":null,\"type\":[\"null\",\"string\"]}]},{\"type\":\"" +
				"record\",\"name\":\"CircularArea\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name" +
				"\":\"coord\",\"type\":\"Coord\"},{\"name\":\"radius\",\"type\":\"double\"},{\"name\":\"distanceUni" +
				"t\",\"default\":null,\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"DistanceUnit\",\"namespace" +
				"\":\"eu.driver.model.mlp\",\"symbols\":[\"meter\"]}]},{\"name\":\"attr_gid\",\"default\":null" +
				",\"type\":[\"null\",\"string\"]},{\"name\":\"attr_srsName\",\"default\":null,\"type\":[\"null\"," +
				"\"string\"]}]},{\"type\":\"record\",\"name\":\"CircularArcArea\",\"namespace\":\"eu.driver.mo" +
				"del.mlp\",\"fields\":[{\"name\":\"coord\",\"type\":\"Coord\"},{\"name\":\"inRadius\",\"type\":\"do" +
				"uble\"},{\"name\":\"outRadius\",\"type\":\"double\"},{\"name\":\"startAngle\",\"type\":\"double\"" +
				"},{\"name\":\"stopAngle\",\"type\":\"double\"},{\"name\":\"angularUnit\",\"default\":null,\"typ" +
				"e\":[\"null\",{\"type\":\"enum\",\"name\":\"AngularUnit\",\"namespace\":\"eu.driver.model.mlp\"" +
				",\"symbols\":[\"Degrees\",\"Radians\"]}]},{\"name\":\"distanceUnit\",\"default\":null,\"type\"" +
				":[\"null\",\"DistanceUnit\"]},{\"name\":\"attr_gid\",\"default\":null,\"type\":[\"null\",\"stri" +
				"ng\"]},{\"name\":\"attr_srsName\",\"default\":null,\"type\":[\"null\",\"string\"]}]},{\"type\":" +
				"\"record\",\"name\":\"EllipticalArea\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"n" +
				"ame\":\"coord\",\"type\":\"Coord\"},{\"name\":\"angle\",\"type\":\"double\"},{\"name\":\"semiMajor" +
				"\",\"type\":\"double\"},{\"name\":\"semiMinor\",\"type\":\"double\"},{\"name\":\"stopAngle\",\"typ" +
				"e\":\"double\"},{\"name\":\"angularUnit\",\"default\":null,\"type\":[\"null\",\"AngularUnit\"]}" +
				",{\"name\":\"distanceUnit\",\"default\":null,\"type\":[\"null\",\"DistanceUnit\"]},{\"name\":\"" +
				"attr_gid\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"attr_srsName\",\"defau" +
				"lt\":null,\"type\":[\"null\",\"string\"]}]}]},{\"name\":\"alt_alt_acc\",\"default\":null,\"typ" +
				"e\":[\"null\",{\"type\":\"record\",\"name\":\"Alt\",\"namespace\":\"eu.driver.model.mlp\",\"fiel" +
				"ds\":[{\"name\":\"alt\",\"doc\":\"Altitude in meters\",\"type\":\"int\"}]},{\"type\":\"record\",\"" +
				"name\":\"AltAcc\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"alt_acc\",\"do" +
				"c\":\"Accuracy of Altitude in meters\",\"default\":null,\"type\":[\"null\",\"int\"]}]}]},{\"" +
				"name\":\"speed\",\"doc\":\"Speed in m/s\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\"" +
				":\"direction\",\"doc\":\"Direction of movement in degrees\",\"default\":null,\"type\":[\"nu" +
				"ll\",\"int\"]},{\"name\":\"lev_conf\",\"doc\":\"Probability in percent that the Mobile Sta" +
				"tion is located in the position area that is returned\",\"default\":null,\"type\":[\"n" +
				"ull\",\"int\"]}]},{\"type\":\"record\",\"name\":\"Poserr\",\"namespace\":\"eu.driver.model.mlp" +
				"\",\"fields\":[{\"name\":\"result\",\"type\":{\"type\":\"record\",\"name\":\"Result\",\"namespace\"" +
				":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"result\",\"doc\":\"See MLP 3.1 specificati" +
				"ons chapter 5.4 on Result Codes\",\"type\":{\"type\":\"enum\",\"name\":\"ResultEnum\",\"name" +
				"space\":\"eu.driver.model.mlp\",\"symbols\":[\"OK\",\"SYSTEM_FAILURE\",\"UNSPECIFIED_ERROR" +
				"\",\"UNAUTHORIZED_APPLICATION\",\"UNKNOWN_SUBSCRIBER\",\"ABSENT_SUBSCRIBER\",\"POSITION_" +
				"METHOD_FAILURE\",\"CONGESTION_IN_LOCATION_SERVER\",\"CONGESTION_IN_MOBILE_NETWORK\",\"" +
				"UNSUPPORTED_VERSION\",\"TOO_MANY_POSITION_ITEMS\",\"FORMAT_ERROR\",\"SYNTAX_ERROR\",\"PR" +
				"OTOCOL_ELEMENT_NOT_SUPPORTED\",\"SERVICE_NOT_SUPPORTED\",\"PROTOCOL_ELEMENT_ATTRIBUT" +
				"E_NOT_SUPPORTED\",\"INVALID_PROTOCOL_ELEMENT_VALUE\",\"INVALID_PROTOCOL_ELEMENT_ATTR" +
				"IBUTE_VALUE\",\"PROTOCOL_ELEMENT_VALUE_NOT_SUPPORTED\",\"PROTOCOL_ELEMENT_ATTRIBUTE_" +
				"VALUE_NOT_SUPPORTED\",\"QOP_NOT_ATTAINABLE\",\"POSITIONING_NOT_ALLOWED\",\"DISALLOWED_" +
				"BY_LOCAL_REGULATIONS\",\"MISCONFIGURATION_OF_LOCATION_SERVER\"]}},{\"name\":\"attr_res" +
				"id\",\"doc\":\"See MLP 3.1 specifications chapter 5.4 on Result Codes\",\"type\":\"strin" +
				"g\"}]}},{\"name\":\"add_info\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"time" +
				"\",\"type\":\"Time\"}]}]}]}");
		private eu.driver.model.mlp.Msid _msid;
		private object _pd_poserr;
		public virtual Schema Schema
		{
			get
			{
				return Pos._SCHEMA;
			}
		}
		public eu.driver.model.mlp.Msid msid
		{
			get
			{
				return this._msid;
			}
			set
			{
				this._msid = value;
			}
		}
		public object pd_poserr
		{
			get
			{
				return this._pd_poserr;
			}
			set
			{
				this._pd_poserr = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.msid;
			case 1: return this.pd_poserr;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.msid = (eu.driver.model.mlp.Msid)fieldValue; break;
			case 1: this.pd_poserr = (System.Object)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
