// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.mlp
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Pos : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Pos\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\"" +
				":\"msid\",\"type\":{\"type\":\"record\",\"name\":\"Msid\",\"namespace\":\"eu.driver.model.mlp\"," +
				"\"fields\":[{\"name\":\"msid\",\"type\":\"string\"},{\"name\":\"attr_type\",\"type\":{\"type\":\"en" +
				"um\",\"name\":\"AttrType\",\"namespace\":\"eu.driver.model.mlp\",\"symbols\":[\"MSISDN\",\"IMS" +
				"I\",\"IMEI\",\"MIN\",\"MDN\",\"EME_MSID\",\"ASID\",\"OPE_ID\",\"IPV4\",\"IPV6\",\"SESSID\"]}},{\"nam" +
				"e\":\"attr_enc\",\"type\":{\"type\":\"enum\",\"name\":\"AttrEnc\",\"namespace\":\"eu.driver.mode" +
				"l.mlp\",\"symbols\":[\"ASC\",\"CRP\"]}}]}},{\"name\":\"pd\",\"default\":null,\"type\":[\"null\",{" +
				"\"type\":\"record\",\"name\":\"Pd\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":" +
				"\"time\",\"type\":{\"type\":\"record\",\"name\":\"Time\",\"namespace\":\"eu.driver.model.mlp\",\"" +
				"fields\":[{\"name\":\"time\",\"doc\":\"UTC Timestamp in milliseconds. Original MLP uses " +
				"String: yyyyMMddhhmmss\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":" +
				"\"attr_utc_off\",\"doc\":\"Specifies the UTC [UTC] offset in hours and minutes. Posit" +
				"ive values indicate time zones east of Greenwich.\",\"default\":\"0000\",\"type\":\"stri" +
				"ng\"}]}},{\"name\":\"shape\",\"doc\":\"TODO: add  MultiLineString | MultiPoint | MultiPo" +
				"lygon if they are needed\",\"type\":[{\"type\":\"record\",\"name\":\"Point\",\"namespace\":\"e" +
				"u.driver.model.mlp\",\"fields\":[{\"name\":\"coord\",\"type\":{\"type\":\"record\",\"name\":\"Co" +
				"ord\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"X\",\"doc\":\"The first co" +
				"ordinate in a coordinate system (30 27 45.3N)\",\"type\":\"string\"},{\"name\":\"Y\",\"doc" +
				"\":\"Second ordinate in a coordinate.system (45 25 52.9E). This is optional if it " +
				"is a linear coordinate system.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\"" +
				":\"Z\",\"doc\":\"Third ordinate in a coordinate system which has at least three ordin" +
				"ates.\",\"default\":null,\"type\":[\"null\",\"string\"]}]}},{\"name\":\"attr_gid\",\"default\":" +
				"null,\"type\":[\"null\",\"string\"]},{\"name\":\"attr_srsName\",\"default\":null,\"type\":[\"nu" +
				"ll\",\"string\"]}]},{\"type\":\"record\",\"name\":\"LineString\",\"namespace\":\"eu.driver.mod" +
				"el.mlp\",\"fields\":[{\"name\":\"coord\",\"doc\":\"Must contain at least 2 coordinates\",\"t" +
				"ype\":{\"type\":\"array\",\"items\":\"Coord\"}},{\"name\":\"attr_gid\",\"default\":null,\"type\":" +
				"[\"null\",\"string\"]},{\"name\":\"attr_srsName\",\"default\":null,\"type\":[\"null\",\"string\"" +
				"]}]},{\"type\":\"record\",\"name\":\"Polygon\",\"namespace\":\"eu.driver.model.mlp\",\"fields" +
				"\":[{\"name\":\"outerBoundaryIs\",\"type\":{\"type\":\"record\",\"name\":\"LinearRing\",\"namesp" +
				"ace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"coords\",\"doc\":\"Must contain at lea" +
				"st 3 coordinates\",\"type\":{\"type\":\"array\",\"items\":\"Coord\"}}]}},{\"name\":\"innerBoun" +
				"daryIs\",\"default\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":\"LinearRing\"}]},{\"" +
				"name\":\"attr_gid\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"attr_srsName\"" +
				",\"default\":null,\"type\":[\"null\",\"string\"]}]},{\"type\":\"record\",\"name\":\"Box\",\"names" +
				"pace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"coordTopLeft\",\"type\":\"Coord\"},{\"n" +
				"ame\":\"coordBottomRight\",\"type\":\"Coord\"},{\"name\":\"attr_gid\",\"default\":null,\"type\"" +
				":[\"null\",\"string\"]},{\"name\":\"attr_srsName\",\"default\":null,\"type\":[\"null\",\"string" +
				"\"]}]},{\"type\":\"record\",\"name\":\"CircularArea\",\"namespace\":\"eu.driver.model.mlp\",\"" +
				"fields\":[{\"name\":\"coord\",\"type\":\"Coord\"},{\"name\":\"radius\",\"type\":\"double\"},{\"nam" +
				"e\":\"distanceUnit\",\"default\":null,\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"DistanceU" +
				"nit\",\"namespace\":\"eu.driver.model.mlp\",\"symbols\":[\"meter\"]}]},{\"name\":\"attr_gid\"" +
				",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"attr_srsName\",\"default\":null," +
				"\"type\":[\"null\",\"string\"]}]},{\"type\":\"record\",\"name\":\"CircularArcArea\",\"namespace" +
				"\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"coord\",\"type\":\"Coord\"},{\"name\":\"inRad" +
				"ius\",\"type\":\"double\"},{\"name\":\"outRadius\",\"type\":\"double\"},{\"name\":\"startAngle\"," +
				"\"type\":\"double\"},{\"name\":\"stopAngle\",\"type\":\"double\"},{\"name\":\"angularUnit\",\"def" +
				"ault\":null,\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"AngularUnit\",\"namespace\":\"eu.dr" +
				"iver.model.mlp\",\"symbols\":[\"Degrees\",\"Radians\"]}]},{\"name\":\"distanceUnit\",\"defau" +
				"lt\":null,\"type\":[\"null\",\"DistanceUnit\"]},{\"name\":\"attr_gid\",\"default\":null,\"type" +
				"\":[\"null\",\"string\"]},{\"name\":\"attr_srsName\",\"default\":null,\"type\":[\"null\",\"strin" +
				"g\"]}]},{\"type\":\"record\",\"name\":\"EllipticalArea\",\"namespace\":\"eu.driver.model.mlp" +
				"\",\"fields\":[{\"name\":\"coord\",\"type\":\"Coord\"},{\"name\":\"angle\",\"type\":\"double\"},{\"n" +
				"ame\":\"semiMajor\",\"type\":\"double\"},{\"name\":\"semiMinor\",\"type\":\"double\"},{\"name\":\"" +
				"stopAngle\",\"type\":\"double\"},{\"name\":\"angularUnit\",\"default\":null,\"type\":[\"null\"," +
				"\"AngularUnit\"]},{\"name\":\"distanceUnit\",\"default\":null,\"type\":[\"null\",\"DistanceUn" +
				"it\"]},{\"name\":\"attr_gid\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"attr_" +
				"srsName\",\"default\":null,\"type\":[\"null\",\"string\"]}]}]},{\"name\":\"alt\",\"default\":nu" +
				"ll,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Alt\",\"namespace\":\"eu.driver.model.mlp" +
				"\",\"fields\":[{\"name\":\"alt\",\"doc\":\"Altitude in meters\",\"type\":\"int\"}]}]},{\"name\":\"" +
				"altAcc\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"AltAcc\",\"namespac" +
				"e\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"alt_acc\",\"doc\":\"Accuracy of Altitude" +
				" in meters\",\"default\":null,\"type\":[\"null\",\"int\"]}]}]},{\"name\":\"speed\",\"doc\":\"Spe" +
				"ed in m/s\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"direction\",\"doc\":\"Dire" +
				"ction of movement in degrees\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"lev" +
				"_conf\",\"doc\":\"Probability in percent that the Mobile Station is located in the p" +
				"osition area that is returned\",\"default\":null,\"type\":[\"null\",\"int\"]}]}]},{\"name\"" +
				":\"poserr\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Poserr\",\"namesp" +
				"ace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"result\",\"type\":{\"type\":\"record\",\"n" +
				"ame\":\"Result\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"result\",\"doc\"" +
				":\"See MLP 3.1 specifications chapter 5.4 on Result Codes\",\"type\":{\"type\":\"enum\"," +
				"\"name\":\"ResultEnum\",\"namespace\":\"eu.driver.model.mlp\",\"symbols\":[\"OK\",\"SYSTEM_FA" +
				"ILURE\",\"UNSPECIFIED_ERROR\",\"UNAUTHORIZED_APPLICATION\",\"UNKNOWN_SUBSCRIBER\",\"ABSE" +
				"NT_SUBSCRIBER\",\"POSITION_METHOD_FAILURE\",\"CONGESTION_IN_LOCATION_SERVER\",\"CONGES" +
				"TION_IN_MOBILE_NETWORK\",\"UNSUPPORTED_VERSION\",\"TOO_MANY_POSITION_ITEMS\",\"FORMAT_" +
				"ERROR\",\"SYNTAX_ERROR\",\"PROTOCOL_ELEMENT_NOT_SUPPORTED\",\"SERVICE_NOT_SUPPORTED\",\"" +
				"PROTOCOL_ELEMENT_ATTRIBUTE_NOT_SUPPORTED\",\"INVALID_PROTOCOL_ELEMENT_VALUE\",\"INVA" +
				"LID_PROTOCOL_ELEMENT_ATTRIBUTE_VALUE\",\"PROTOCOL_ELEMENT_VALUE_NOT_SUPPORTED\",\"PR" +
				"OTOCOL_ELEMENT_ATTRIBUTE_VALUE_NOT_SUPPORTED\",\"QOP_NOT_ATTAINABLE\",\"POSITIONING_" +
				"NOT_ALLOWED\",\"DISALLOWED_BY_LOCAL_REGULATIONS\",\"MISCONFIGURATION_OF_LOCATION_SER" +
				"VER\"]}},{\"name\":\"attr_resid\",\"doc\":\"See MLP 3.1 specifications chapter 5.4 on Re" +
				"sult Codes\",\"type\":\"string\"}]}},{\"name\":\"add_info\",\"default\":null,\"type\":[\"null\"" +
				",\"string\"]},{\"name\":\"time\",\"type\":\"Time\"}]}]}]}");
		private eu.driver.model.mlp.Msid _msid;
		private eu.driver.model.mlp.Pd _pd;
		private eu.driver.model.mlp.Poserr _poserr;
		public virtual Schema Schema
		{
			get
			{
				return Pos._SCHEMA;
			}
		}
		public eu.driver.model.mlp.Msid msid
		{
			get
			{
				return this._msid;
			}
			set
			{
				this._msid = value;
			}
		}
		public eu.driver.model.mlp.Pd pd
		{
			get
			{
				return this._pd;
			}
			set
			{
				this._pd = value;
			}
		}
		public eu.driver.model.mlp.Poserr poserr
		{
			get
			{
				return this._poserr;
			}
			set
			{
				this._poserr = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.msid;
			case 1: return this.pd;
			case 2: return this.poserr;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.msid = (eu.driver.model.mlp.Msid)fieldValue; break;
			case 1: this.pd = (eu.driver.model.mlp.Pd)fieldValue; break;
			case 2: this.poserr = (eu.driver.model.mlp.Poserr)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
