// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.mlp
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Poserr : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Poserr\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"na" +
				"me\":\"result\",\"type\":{\"type\":\"record\",\"name\":\"Result\",\"namespace\":\"eu.driver.mode" +
				"l.mlp\",\"fields\":[{\"name\":\"result\",\"doc\":\"See MLP 3.1 specifications chapter 5.4 " +
				"on Result Codes\",\"type\":{\"type\":\"enum\",\"name\":\"ResultEnum\",\"namespace\":\"eu.drive" +
				"r.model.mlp\",\"symbols\":[\"OK\",\"SYSTEM_FAILURE\",\"UNSPECIFIED_ERROR\",\"UNAUTHORIZED_" +
				"APPLICATION\",\"UNKNOWN_SUBSCRIBER\",\"ABSENT_SUBSCRIBER\",\"POSITION_METHOD_FAILURE\"," +
				"\"CONGESTION_IN_LOCATION_SERVER\",\"CONGESTION_IN_MOBILE_NETWORK\",\"UNSUPPORTED_VERS" +
				"ION\",\"TOO_MANY_POSITION_ITEMS\",\"FORMAT_ERROR\",\"SYNTAX_ERROR\",\"PROTOCOL_ELEMENT_N" +
				"OT_SUPPORTED\",\"SERVICE_NOT_SUPPORTED\",\"PROTOCOL_ELEMENT_ATTRIBUTE_NOT_SUPPORTED\"" +
				",\"INVALID_PROTOCOL_ELEMENT_VALUE\",\"INVALID_PROTOCOL_ELEMENT_ATTRIBUTE_VALUE\",\"PR" +
				"OTOCOL_ELEMENT_VALUE_NOT_SUPPORTED\",\"PROTOCOL_ELEMENT_ATTRIBUTE_VALUE_NOT_SUPPOR" +
				"TED\",\"QOP_NOT_ATTAINABLE\",\"POSITIONING_NOT_ALLOWED\",\"DISALLOWED_BY_LOCAL_REGULAT" +
				"IONS\",\"MISCONFIGURATION_OF_LOCATION_SERVER\"]}},{\"name\":\"attr_resid\",\"doc\":\"See M" +
				"LP 3.1 specifications chapter 5.4 on Result Codes\",\"type\":\"string\"}]}},{\"name\":\"" +
				"add_info\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"time\",\"type\":{\"type\"" +
				":\"record\",\"name\":\"Time\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"tim" +
				"e\",\"doc\":\"UTC Timestamp in milliseconds. Original MLP uses String: yyyyMMddhhmms" +
				"s\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"attr_utc_off\",\"doc\":" +
				"\"Specifies the UTC [UTC] offset in hours and minutes. Positive values indicate t" +
				"ime zones east of Greenwich.\",\"default\":\"0000\",\"type\":\"string\"}]}}]}");
		private eu.driver.model.mlp.Result _result;
		private string _add_info;
		private eu.driver.model.mlp.Time _time;
		public virtual Schema Schema
		{
			get
			{
				return Poserr._SCHEMA;
			}
		}
		public eu.driver.model.mlp.Result result
		{
			get
			{
				return this._result;
			}
			set
			{
				this._result = value;
			}
		}
		public string add_info
		{
			get
			{
				return this._add_info;
			}
			set
			{
				this._add_info = value;
			}
		}
		public eu.driver.model.mlp.Time time
		{
			get
			{
				return this._time;
			}
			set
			{
				this._time = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.result;
			case 1: return this.add_info;
			case 2: return this.time;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.result = (eu.driver.model.mlp.Result)fieldValue; break;
			case 1: this.add_info = (System.String)fieldValue; break;
			case 2: this.time = (eu.driver.model.mlp.Time)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
