// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.mlp
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class SlRep : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"SlRep\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"nam" +
				"e\":\"attr_ver\",\"default\":\"3.0.0\",\"type\":\"string\"},{\"name\":\"pos\",\"type\":{\"type\":\"r" +
				"ecord\",\"name\":\"Pos\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"msid\",\"" +
				"type\":{\"type\":\"record\",\"name\":\"Msid\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":" +
				"[{\"name\":\"msid\",\"type\":\"string\"},{\"name\":\"attr_type\",\"type\":{\"type\":\"enum\",\"name" +
				"\":\"AttrType\",\"namespace\":\"eu.driver.model.mlp\",\"symbols\":[\"MSISDN\",\"IMSI\",\"IMEI\"" +
				",\"MIN\",\"MDN\",\"EME_MSID\",\"ASID\",\"OPE_ID\",\"IPV4\",\"IPV6\",\"SESSID\"]}},{\"name\":\"attr_" +
				"enc\",\"type\":{\"type\":\"enum\",\"name\":\"AttrEnc\",\"namespace\":\"eu.driver.model.mlp\",\"s" +
				"ymbols\":[\"ASC\",\"CRP\"]}}]}},{\"name\":\"pd\",\"default\":null,\"type\":[\"null\",{\"type\":\"r" +
				"ecord\",\"name\":\"Pd\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"time\",\"t" +
				"ype\":{\"type\":\"record\",\"name\":\"Time\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[" +
				"{\"name\":\"time\",\"doc\":\"UTC Timestamp in milliseconds. Original MLP uses String: y" +
				"yyyMMddhhmmss\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"attr_utc" +
				"_off\",\"doc\":\"Specifies the UTC [UTC] offset in hours and minutes. Positive value" +
				"s indicate time zones east of Greenwich.\",\"default\":\"0000\",\"type\":\"string\"}]}},{" +
				"\"name\":\"shape\",\"doc\":\"TODO: add  MultiLineString | MultiPoint | MultiPolygon if " +
				"they are needed\",\"type\":[{\"type\":\"record\",\"name\":\"Point\",\"namespace\":\"eu.driver." +
				"model.mlp\",\"fields\":[{\"name\":\"coord\",\"type\":{\"type\":\"record\",\"name\":\"Coord\",\"nam" +
				"espace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"X\",\"doc\":\"The first coordinate " +
				"in a coordinate system (30 27 45.3N)\",\"type\":\"string\"},{\"name\":\"Y\",\"doc\":\"Second" +
				" ordinate in a coordinate.system (45 25 52.9E). This is optional if it is a line" +
				"ar coordinate system.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Z\",\"doc" +
				"\":\"Third ordinate in a coordinate system which has at least three ordinates.\",\"d" +
				"efault\":null,\"type\":[\"null\",\"string\"]}]}},{\"name\":\"attr_gid\",\"default\":null,\"typ" +
				"e\":[\"null\",\"string\"]},{\"name\":\"attr_srsName\",\"default\":null,\"type\":[\"null\",\"stri" +
				"ng\"]}]},{\"type\":\"record\",\"name\":\"LineString\",\"namespace\":\"eu.driver.model.mlp\",\"" +
				"fields\":[{\"name\":\"coord\",\"doc\":\"Must contain at least 2 coordinates\",\"type\":{\"ty" +
				"pe\":\"array\",\"items\":\"Coord\"}},{\"name\":\"attr_gid\",\"default\":null,\"type\":[\"null\",\"" +
				"string\"]},{\"name\":\"attr_srsName\",\"default\":null,\"type\":[\"null\",\"string\"]}]},{\"ty" +
				"pe\":\"record\",\"name\":\"Polygon\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name" +
				"\":\"outerBoundaryIs\",\"type\":{\"type\":\"record\",\"name\":\"LinearRing\",\"namespace\":\"eu." +
				"driver.model.mlp\",\"fields\":[{\"name\":\"coords\",\"doc\":\"Must contain at least 3 coor" +
				"dinates\",\"type\":{\"type\":\"array\",\"items\":\"Coord\"}}]}},{\"name\":\"innerBoundaryIs\",\"" +
				"default\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":\"LinearRing\"}]},{\"name\":\"at" +
				"tr_gid\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"attr_srsName\",\"default" +
				"\":null,\"type\":[\"null\",\"string\"]}]},{\"type\":\"record\",\"name\":\"Box\",\"namespace\":\"eu" +
				".driver.model.mlp\",\"fields\":[{\"name\":\"coordTopLeft\",\"type\":\"Coord\"},{\"name\":\"coo" +
				"rdBottomRight\",\"type\":\"Coord\"},{\"name\":\"attr_gid\",\"default\":null,\"type\":[\"null\"," +
				"\"string\"]},{\"name\":\"attr_srsName\",\"default\":null,\"type\":[\"null\",\"string\"]}]},{\"t" +
				"ype\":\"record\",\"name\":\"CircularArea\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[" +
				"{\"name\":\"coord\",\"type\":\"Coord\"},{\"name\":\"radius\",\"type\":\"double\"},{\"name\":\"dista" +
				"nceUnit\",\"default\":null,\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"DistanceUnit\",\"nam" +
				"espace\":\"eu.driver.model.mlp\",\"symbols\":[\"meter\"]}]},{\"name\":\"attr_gid\",\"default" +
				"\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"attr_srsName\",\"default\":null,\"type\":[\"" +
				"null\",\"string\"]}]},{\"type\":\"record\",\"name\":\"CircularArcArea\",\"namespace\":\"eu.dri" +
				"ver.model.mlp\",\"fields\":[{\"name\":\"coord\",\"type\":\"Coord\"},{\"name\":\"inRadius\",\"typ" +
				"e\":\"double\"},{\"name\":\"outRadius\",\"type\":\"double\"},{\"name\":\"startAngle\",\"type\":\"d" +
				"ouble\"},{\"name\":\"stopAngle\",\"type\":\"double\"},{\"name\":\"angularUnit\",\"default\":nul" +
				"l,\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"AngularUnit\",\"namespace\":\"eu.driver.mode" +
				"l.mlp\",\"symbols\":[\"Degrees\",\"Radians\"]}]},{\"name\":\"distanceUnit\",\"default\":null," +
				"\"type\":[\"null\",\"DistanceUnit\"]},{\"name\":\"attr_gid\",\"default\":null,\"type\":[\"null\"" +
				",\"string\"]},{\"name\":\"attr_srsName\",\"default\":null,\"type\":[\"null\",\"string\"]}]},{\"" +
				"type\":\"record\",\"name\":\"EllipticalArea\",\"namespace\":\"eu.driver.model.mlp\",\"fields" +
				"\":[{\"name\":\"coord\",\"type\":\"Coord\"},{\"name\":\"angle\",\"type\":\"double\"},{\"name\":\"sem" +
				"iMajor\",\"type\":\"double\"},{\"name\":\"semiMinor\",\"type\":\"double\"},{\"name\":\"stopAngle" +
				"\",\"type\":\"double\"},{\"name\":\"angularUnit\",\"default\":null,\"type\":[\"null\",\"AngularU" +
				"nit\"]},{\"name\":\"distanceUnit\",\"default\":null,\"type\":[\"null\",\"DistanceUnit\"]},{\"n" +
				"ame\":\"attr_gid\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"attr_srsName\"," +
				"\"default\":null,\"type\":[\"null\",\"string\"]}]}]},{\"name\":\"alt\",\"default\":null,\"type\"" +
				":[\"null\",{\"type\":\"record\",\"name\":\"Alt\",\"namespace\":\"eu.driver.model.mlp\",\"fields" +
				"\":[{\"name\":\"alt\",\"doc\":\"Altitude in meters\",\"type\":\"int\"}]}]},{\"name\":\"altAcc\",\"" +
				"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"AltAcc\",\"namespace\":\"eu.dr" +
				"iver.model.mlp\",\"fields\":[{\"name\":\"alt_acc\",\"doc\":\"Accuracy of Altitude in meter" +
				"s\",\"default\":null,\"type\":[\"null\",\"int\"]}]}]},{\"name\":\"speed\",\"doc\":\"Speed in m/s" +
				"\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"direction\",\"doc\":\"Direction of " +
				"movement in degrees\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"lev_conf\",\"d" +
				"oc\":\"Probability in percent that the Mobile Station is located in the position a" +
				"rea that is returned\",\"default\":null,\"type\":[\"null\",\"int\"]}]}]},{\"name\":\"poserr\"" +
				",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Poserr\",\"namespace\":\"eu." +
				"driver.model.mlp\",\"fields\":[{\"name\":\"result\",\"type\":{\"type\":\"record\",\"name\":\"Res" +
				"ult\",\"namespace\":\"eu.driver.model.mlp\",\"fields\":[{\"name\":\"result\",\"doc\":\"See MLP" +
				" 3.1 specifications chapter 5.4 on Result Codes\",\"type\":{\"type\":\"enum\",\"name\":\"R" +
				"esultEnum\",\"namespace\":\"eu.driver.model.mlp\",\"symbols\":[\"OK\",\"SYSTEM_FAILURE\",\"U" +
				"NSPECIFIED_ERROR\",\"UNAUTHORIZED_APPLICATION\",\"UNKNOWN_SUBSCRIBER\",\"ABSENT_SUBSCR" +
				"IBER\",\"POSITION_METHOD_FAILURE\",\"CONGESTION_IN_LOCATION_SERVER\",\"CONGESTION_IN_M" +
				"OBILE_NETWORK\",\"UNSUPPORTED_VERSION\",\"TOO_MANY_POSITION_ITEMS\",\"FORMAT_ERROR\",\"S" +
				"YNTAX_ERROR\",\"PROTOCOL_ELEMENT_NOT_SUPPORTED\",\"SERVICE_NOT_SUPPORTED\",\"PROTOCOL_" +
				"ELEMENT_ATTRIBUTE_NOT_SUPPORTED\",\"INVALID_PROTOCOL_ELEMENT_VALUE\",\"INVALID_PROTO" +
				"COL_ELEMENT_ATTRIBUTE_VALUE\",\"PROTOCOL_ELEMENT_VALUE_NOT_SUPPORTED\",\"PROTOCOL_EL" +
				"EMENT_ATTRIBUTE_VALUE_NOT_SUPPORTED\",\"QOP_NOT_ATTAINABLE\",\"POSITIONING_NOT_ALLOW" +
				"ED\",\"DISALLOWED_BY_LOCAL_REGULATIONS\",\"MISCONFIGURATION_OF_LOCATION_SERVER\"]}},{" +
				"\"name\":\"attr_resid\",\"doc\":\"See MLP 3.1 specifications chapter 5.4 on Result Code" +
				"s\",\"type\":\"string\"}]}},{\"name\":\"add_info\",\"default\":null,\"type\":[\"null\",\"string\"" +
				"]},{\"name\":\"time\",\"type\":\"Time\"}]}]}]}}]}");
		private string _attr_ver;
		private eu.driver.model.mlp.Pos _pos;
		public virtual Schema Schema
		{
			get
			{
				return SlRep._SCHEMA;
			}
		}
		public string attr_ver
		{
			get
			{
				return this._attr_ver;
			}
			set
			{
				this._attr_ver = value;
			}
		}
		public eu.driver.model.mlp.Pos pos
		{
			get
			{
				return this._pos;
			}
			set
			{
				this._pos = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.attr_ver;
			case 1: return this.pos;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.attr_ver = (System.String)fieldValue; break;
			case 1: this.pos = (eu.driver.model.mlp.Pos)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
